/*
 * prod-code — Remote code intelligence
 * Copyright (c) 2026 Alexander Panasenko
 *
 * Contact: alex@prod.codes
 * Author: https://prod.codes/about/
 * Project: https://github.com/alex09x/prod-code
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

use super::lang::{Language, is_ident};
use super::types::{PolyToken, PolyTokenKind};

pub fn tokenize_polyglot(text: &str, lang: Language) -> Vec<PolyToken> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let c = text[i..].chars().next().unwrap_or(' ');
        let len = c.len_utf8();
        if c.is_whitespace() {
            i += len;
        } else if lang == Language::Python && text[i..].starts_with('#') {
            i = text[i..].find('\n').map_or(text.len(), |n| i + n);
        } else if lang != Language::Python && text[i..].starts_with("//") {
            i = text[i..].find('\n').map_or(text.len(), |n| i + n);
        } else if lang != Language::Python && text[i..].starts_with("/*") {
            i = text[i..].find("*/").map_or(text.len(), |n| i + n + 2);
        } else if c.is_ascii_digit() {
            let mut j = i;
            while j < bytes.len()
                && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_' || bytes[j] == b'.')
            {
                if bytes[j] == b'.' && bytes.get(j + 1) == Some(&b'.') {
                    break;
                }
                j += 1;
            }
            out.push(PolyToken {
                kind: PolyTokenKind::Number,
                start: i,
                end: j,
                text: text[i..j].to_string(),
            });
            i = j;
        } else if c == '"'
            || c == '`'
            || (c == '\''
                && lang != Language::Rust
                && lang != Language::Cpp
                && lang != Language::C
                && lang != Language::Zig)
        {
            let quote = c;
            let mut j = i + 1;
            while j < bytes.len() && text[j..].chars().next().unwrap_or(' ') != quote {
                let clen = text[j..].chars().next().map_or(1, |ch| ch.len_utf8());
                if bytes[j] == b'\\' {
                    j += 1;
                    if j < bytes.len() {
                        let elen = text[j..].chars().next().map_or(1, |ch| ch.len_utf8());
                        j += elen;
                    }
                } else {
                    j += clen;
                }
            }
            let j = if j < bytes.len() { j + 1 } else { bytes.len() };
            out.push(PolyToken {
                kind: PolyTokenKind::Str,
                start: i,
                end: j,
                text: text[i..j].to_string(),
            });
            i = j;
        } else if c == '\'' {
            let mut j = i + 1;
            while j < bytes.len() && bytes[j] != b'\'' {
                j += if bytes[j] == b'\\' { 2 } else { 1 };
            }
            let j = (j + 1).min(bytes.len());
            out.push(PolyToken {
                kind: PolyTokenKind::Char,
                start: i,
                end: j,
                text: text[i..j].to_string(),
            });
            i = j;
        } else if is_ident(c) && !c.is_ascii_digit() {
            let mut j = i;
            while let Some(ch) = text[j..].chars().next() {
                if !is_ident(ch) {
                    break;
                }
                j += ch.len_utf8();
            }
            out.push(PolyToken {
                kind: PolyTokenKind::Word,
                start: i,
                end: j,
                text: text[i..j].to_string(),
            });
            i = j;
        } else {
            let two = if i + 2 <= bytes.len() && c.is_ascii() && bytes[i + 1].is_ascii() {
                &text[i..i + 2]
            } else {
                ""
            };
            let punct_len = match two {
                "->" | "=>" | "::" | ":=" | "==" | "!=" | "<=" | ">=" | "&&" | "||" | "++"
                | "--" | "+=" | "-=" | "*=" | "/=" => 2,
                _ => len,
            };
            out.push(PolyToken {
                kind: PolyTokenKind::Punct,
                start: i,
                end: i + punct_len,
                text: text[i..i + punct_len].to_string(),
            });
            i += punct_len;
        }
    }
    out
}

pub fn is_keyword(word: &str, lang: Language) -> bool {
    match lang {
        Language::Python => matches!(
            word,
            "and"
                | "as"
                | "assert"
                | "async"
                | "await"
                | "break"
                | "case"
                | "class"
                | "continue"
                | "def"
                | "del"
                | "elif"
                | "else"
                | "except"
                | "finally"
                | "for"
                | "from"
                | "global"
                | "if"
                | "import"
                | "in"
                | "is"
                | "lambda"
                | "match"
                | "nonlocal"
                | "not"
                | "or"
                | "pass"
                | "raise"
                | "return"
                | "try"
                | "while"
                | "with"
                | "yield"
                | "True"
                | "False"
                | "None"
                | "self"
        ),
        Language::TypeScript | Language::JavaScript => matches!(
            word,
            "break"
                | "case"
                | "catch"
                | "class"
                | "const"
                | "continue"
                | "debugger"
                | "default"
                | "delete"
                | "do"
                | "else"
                | "export"
                | "extends"
                | "finally"
                | "for"
                | "function"
                | "if"
                | "import"
                | "in"
                | "instanceof"
                | "new"
                | "return"
                | "super"
                | "switch"
                | "this"
                | "throw"
                | "try"
                | "typeof"
                | "var"
                | "void"
                | "while"
                | "with"
                | "yield"
                | "let"
                | "static"
                | "enum"
                | "await"
                | "async"
                | "from"
                | "as"
                | "true"
                | "false"
                | "null"
                | "undefined"
                | "number"
                | "string"
                | "boolean"
                | "any"
                | "never"
                | "unknown"
                | "type"
                | "interface"
                | "implements"
                | "declare"
                | "readonly"
        ),
        Language::Go => matches!(
            word,
            "break"
                | "default"
                | "func"
                | "interface"
                | "select"
                | "case"
                | "defer"
                | "go"
                | "map"
                | "struct"
                | "chan"
                | "else"
                | "goto"
                | "package"
                | "switch"
                | "const"
                | "fallthrough"
                | "if"
                | "range"
                | "type"
                | "continue"
                | "for"
                | "import"
                | "return"
                | "var"
                | "true"
                | "false"
                | "nil"
                | "int"
                | "int8"
                | "int16"
                | "int32"
                | "int64"
                | "uint"
                | "uint8"
                | "uint16"
                | "uint32"
                | "uint64"
                | "string"
                | "float32"
                | "float64"
                | "bool"
                | "byte"
                | "rune"
                | "error"
                | "any"
        ),
        Language::Cpp | Language::C => matches!(
            word,
            "auto"
                | "break"
                | "case"
                | "char"
                | "const"
                | "continue"
                | "default"
                | "do"
                | "double"
                | "else"
                | "enum"
                | "extern"
                | "float"
                | "for"
                | "goto"
                | "if"
                | "int"
                | "long"
                | "register"
                | "return"
                | "short"
                | "signed"
                | "sizeof"
                | "static"
                | "struct"
                | "switch"
                | "typedef"
                | "union"
                | "unsigned"
                | "void"
                | "volatile"
                | "while"
                | "class"
                | "namespace"
                | "new"
                | "delete"
                | "this"
                | "public"
                | "private"
                | "protected"
                | "virtual"
                | "override"
                | "template"
                | "typename"
                | "using"
                | "true"
                | "false"
                | "nullptr"
                | "std"
                | "bool"
                | "size_t"
                | "constexpr"
                | "inline"
        ),
        Language::Swift => matches!(
            word,
            "associatedtype"
                | "class"
                | "deinit"
                | "enum"
                | "extension"
                | "fileprivate"
                | "func"
                | "import"
                | "init"
                | "inout"
                | "internal"
                | "let"
                | "open"
                | "operator"
                | "private"
                | "protocol"
                | "public"
                | "rethrows"
                | "static"
                | "struct"
                | "subscript"
                | "typealias"
                | "var"
                | "break"
                | "case"
                | "continue"
                | "default"
                | "defer"
                | "do"
                | "else"
                | "fallthrough"
                | "for"
                | "guard"
                | "if"
                | "in"
                | "repeat"
                | "return"
                | "switch"
                | "where"
                | "while"
                | "as"
                | "Any"
                | "catch"
                | "false"
                | "is"
                | "nil"
                | "super"
                | "self"
                | "Self"
                | "throw"
                | "throws"
                | "true"
                | "try"
                | "Int"
                | "Double"
                | "Float"
                | "String"
                | "Bool"
        ),
        Language::Rust => matches!(
            word,
            "as" | "break"
                | "const"
                | "continue"
                | "crate"
                | "else"
                | "enum"
                | "extern"
                | "false"
                | "fn"
                | "for"
                | "if"
                | "impl"
                | "in"
                | "let"
                | "loop"
                | "match"
                | "mod"
                | "move"
                | "mut"
                | "pub"
                | "ref"
                | "return"
                | "self"
                | "Self"
                | "static"
                | "struct"
                | "super"
                | "trait"
                | "true"
                | "type"
                | "unsafe"
                | "use"
                | "where"
                | "while"
                | "async"
                | "await"
                | "dyn"
        ),
        Language::Java => matches!(
            word,
            "abstract"
                | "assert"
                | "boolean"
                | "break"
                | "byte"
                | "case"
                | "catch"
                | "char"
                | "class"
                | "const"
                | "continue"
                | "default"
                | "do"
                | "double"
                | "else"
                | "enum"
                | "extends"
                | "final"
                | "finally"
                | "float"
                | "for"
                | "goto"
                | "if"
                | "implements"
                | "import"
                | "instanceof"
                | "int"
                | "interface"
                | "long"
                | "native"
                | "new"
                | "package"
                | "private"
                | "protected"
                | "public"
                | "return"
                | "short"
                | "static"
                | "strictfp"
                | "super"
                | "switch"
                | "synchronized"
                | "this"
                | "throw"
                | "throws"
                | "transient"
                | "try"
                | "void"
                | "volatile"
                | "while"
                | "record"
                | "var"
                | "yield"
                | "sealed"
                | "permits"
                | "non-sealed"
                | "true"
                | "false"
                | "null"
        ),
        Language::Kotlin => matches!(
            word,
            "as" | "break"
                | "class"
                | "continue"
                | "do"
                | "else"
                | "false"
                | "for"
                | "fun"
                | "if"
                | "in"
                | "interface"
                | "is"
                | "null"
                | "object"
                | "package"
                | "return"
                | "super"
                | "this"
                | "throw"
                | "true"
                | "try"
                | "typealias"
                | "typeof"
                | "val"
                | "var"
                | "when"
                | "while"
                | "by"
                | "catch"
                | "constructor"
                | "delegate"
                | "dynamic"
                | "field"
                | "file"
                | "finally"
                | "get"
                | "import"
                | "init"
                | "param"
                | "property"
                | "receiver"
                | "set"
                | "setparam"
                | "where"
                | "actual"
                | "abstract"
                | "annotation"
                | "companion"
                | "const"
                | "crossinline"
                | "data"
                | "enum"
                | "expect"
                | "external"
                | "final"
                | "infix"
                | "inline"
                | "inner"
                | "internal"
                | "lateinit"
                | "noinline"
                | "open"
                | "operator"
                | "out"
                | "override"
                | "private"
                | "protected"
                | "public"
                | "reified"
                | "sealed"
                | "suspend"
                | "tailrec"
                | "vararg"
                | "value"
        ),
        Language::Csharp => matches!(
            word,
            "abstract"
                | "as"
                | "base"
                | "bool"
                | "break"
                | "byte"
                | "case"
                | "catch"
                | "char"
                | "checked"
                | "class"
                | "const"
                | "continue"
                | "decimal"
                | "default"
                | "delegate"
                | "do"
                | "double"
                | "else"
                | "enum"
                | "event"
                | "explicit"
                | "extern"
                | "false"
                | "finally"
                | "fixed"
                | "float"
                | "for"
                | "foreach"
                | "goto"
                | "if"
                | "implicit"
                | "in"
                | "int"
                | "interface"
                | "internal"
                | "is"
                | "lock"
                | "long"
                | "namespace"
                | "new"
                | "null"
                | "object"
                | "operator"
                | "out"
                | "override"
                | "params"
                | "private"
                | "protected"
                | "public"
                | "readonly"
                | "record"
                | "ref"
                | "return"
                | "sbyte"
                | "sealed"
                | "short"
                | "sizeof"
                | "stackalloc"
                | "static"
                | "string"
                | "struct"
                | "switch"
                | "this"
                | "throw"
                | "true"
                | "try"
                | "typeof"
                | "uint"
                | "ulong"
                | "unchecked"
                | "unsafe"
                | "ushort"
                | "using"
                | "virtual"
                | "void"
                | "volatile"
                | "while"
                | "var"
                | "async"
                | "await"
                | "yield"
        ),
        Language::Zig => matches!(
            word,
            "addrspace"
                | "align"
                | "allowzero"
                | "and"
                | "anyframe"
                | "anytype"
                | "asm"
                | "async"
                | "await"
                | "break"
                | "callconv"
                | "catch"
                | "comptime"
                | "const"
                | "continue"
                | "defer"
                | "else"
                | "enum"
                | "errdefer"
                | "error"
                | "export"
                | "extern"
                | "fn"
                | "for"
                | "if"
                | "inline"
                | "noalias"
                | "noinline"
                | "nosuspend"
                | "opaque"
                | "or"
                | "orelse"
                | "packed"
                | "pub"
                | "resume"
                | "return"
                | "linksection"
                | "struct"
                | "suspend"
                | "switch"
                | "test"
                | "threadlocal"
                | "try"
                | "union"
                | "unreachable"
                | "usingnamespace"
                | "var"
                | "volatile"
                | "while"
                | "true"
                | "false"
                | "null"
                | "undefined"
                | "u8"
                | "u16"
                | "u32"
                | "u64"
                | "u128"
                | "usize"
                | "i8"
                | "i16"
                | "i32"
                | "i64"
                | "i128"
                | "isize"
                | "f16"
                | "f32"
                | "f64"
                | "f80"
                | "f128"
                | "c_int"
                | "c_uint"
                | "c_long"
                | "c_ulong"
                | "c_char"
                | "bool"
                | "void"
                | "noreturn"
                | "type"
                | "anyerror"
        ),
    }
}

pub fn is_builtin_or_global(word: &str, lang: Language) -> bool {
    match lang {
        Language::Python => matches!(
            word,
            "print"
                | "len"
                | "range"
                | "sum"
                | "min"
                | "max"
                | "abs"
                | "round"
                | "int"
                | "float"
                | "str"
                | "bool"
                | "list"
                | "dict"
                | "set"
                | "tuple"
                | "open"
                | "isinstance"
                | "issubclass"
                | "type"
                | "zip"
                | "map"
                | "filter"
                | "enumerate"
                | "any"
                | "all"
                | "sorted"
                | "reversed"
                | "id"
                | "repr"
                | "iter"
                | "next"
        ),
        Language::TypeScript | Language::JavaScript => matches!(
            word,
            "console"
                | "Math"
                | "JSON"
                | "Object"
                | "Array"
                | "String"
                | "Number"
                | "Boolean"
                | "Date"
                | "RegExp"
                | "Error"
                | "Promise"
                | "Map"
                | "Set"
                | "WeakMap"
                | "WeakSet"
                | "Symbol"
                | "parseInt"
                | "parseFloat"
                | "isNaN"
                | "isFinite"
                | "encodeURI"
                | "decodeURI"
        ),
        Language::Go => matches!(
            word,
            "fmt"
                | "make"
                | "append"
                | "copy"
                | "delete"
                | "len"
                | "cap"
                | "panic"
                | "recover"
                | "close"
                | "new"
                | "real"
                | "imag"
                | "complex"
                | "print"
                | "println"
        ),
        Language::Cpp | Language::C => matches!(
            word,
            "std"
                | "printf"
                | "scanf"
                | "cout"
                | "cin"
                | "cerr"
                | "endl"
                | "malloc"
                | "free"
                | "sizeof"
                | "memcpy"
                | "memset"
                | "vector"
                | "string"
                | "map"
                | "unordered_map"
                | "set"
                | "shared_ptr"
                | "unique_ptr"
        ),
        Language::Swift => matches!(
            word,
            "print"
                | "min"
                | "max"
                | "abs"
                | "Array"
                | "Dictionary"
                | "Set"
                | "String"
                | "Int"
                | "Double"
                | "Float"
                | "Bool"
                | "fatalError"
                | "precondition"
        ),
        Language::Rust => matches!(
            word,
            "println"
                | "print"
                | "eprintln"
                | "eprint"
                | "format"
                | "vec"
                | "panic"
                | "Some"
                | "None"
                | "Ok"
                | "Err"
                | "Box"
                | "Vec"
                | "String"
                | "Option"
                | "Result"
        ),
        Language::Java => matches!(
            word,
            "System"
                | "String"
                | "Object"
                | "Integer"
                | "Long"
                | "Double"
                | "Float"
                | "Boolean"
                | "Character"
                | "Byte"
                | "Short"
                | "Math"
                | "Arrays"
                | "Collections"
                | "List"
                | "Map"
                | "Set"
                | "Optional"
                | "Objects"
                | "StringBuilder"
                | "StringBuffer"
                | "Exception"
                | "RuntimeException"
                | "Throwable"
                | "Thread"
                | "Runnable"
        ),
        Language::Kotlin => matches!(
            word,
            "println"
                | "print"
                | "require"
                | "check"
                | "error"
                | "assert"
                | "TODO"
                | "run"
                | "let"
                | "also"
                | "apply"
                | "with"
                | "takeIf"
                | "takeUnless"
                | "repeat"
                | "lazy"
                | "emptyList"
                | "listOf"
                | "mutableListOf"
                | "emptySet"
                | "setOf"
                | "mutableSetOf"
                | "emptyMap"
                | "mapOf"
                | "mutableMapOf"
                | "String"
                | "Int"
                | "Long"
                | "Double"
                | "Float"
                | "Boolean"
                | "Byte"
                | "Short"
                | "Char"
                | "Any"
                | "Unit"
                | "Nothing"
                | "Array"
                | "ByteArray"
                | "IntArray"
                | "LongArray"
                | "CharArray"
                | "BooleanArray"
        ),
        Language::Csharp => matches!(
            word,
            "Console"
                | "String"
                | "Object"
                | "Int32"
                | "Int64"
                | "Double"
                | "Single"
                | "Boolean"
                | "Char"
                | "Byte"
                | "Int16"
                | "Math"
                | "Array"
                | "List"
                | "Dictionary"
                | "HashSet"
                | "StringBuilder"
                | "Exception"
                | "Task"
                | "ValueTask"
                | "Action"
                | "Func"
                | "Predicate"
                | "Nullable"
                | "Span"
                | "ReadOnlySpan"
                | "Memory"
        ),
        Language::Zig => matches!(word, "std" | "builtin" | "root" | "assert"),
    }
}
