/*
 * prod-code — Remote code intelligence
 * Copyright (c) 2026 Alexander Panasenko
 *
 * Contact: alex@prod.codes
 * Author: https://prod.codes/about/
 * Project: https://github.com/alex09x/prod-code
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

use prod_code_protocol::FileDelta;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

/// Bytes of output kept per hypothesis unless the request says otherwise.
pub const DEFAULT_TAIL_BYTES: usize = 64 * 1024;
pub(crate) const DEFAULT_TIMEOUT_SECS: u64 = 3600;
pub const OWNERSHIP_LOCK_FILE: &str = ".prod-code-shadow-owner.lock";
pub const HYPOTHESIS_DIR_PREFIX: &str = ".prod-code-hypothesis-";

/// The script every overlay hypothesis runs inside its own user + mount namespace.
pub(crate) const RUN_SCRIPT: &str = r#"#!/bin/sh
# Generated by prod-code for one hypothesis of a shadow run.
set -e
if ! mount -t overlay overlay -o "lowerdir=$SHADOW_LOWER,upperdir=$SHADOW_UPPER,workdir=$SHADOW_WORK" "$SHADOW_LOWER"; then
  exit 1
fi
if [ -n "$SHADOW_MOUNT_STATUS" ]; then
  status_file="$SHADOW_MOUNT_STATUS"
  control_dir="$SHADOW_CONTROL_DIR"
  printf "ok" > "$status_file"
  if [ -n "$control_dir" ] && [ -d "$control_dir" ]; then
    if ! mount -t tmpfs -o size=1m,mode=000 tmpfs "$control_dir"; then
      rm -f "$status_file"
      echo "prod-code: cannot isolate mount control directory" >&2
      exit 1
    fi
  fi
fi
if [ -s "$SHADOW_DELETE" ]; then
  while IFS= read -r p; do rm -f "$SHADOW_LOWER/$p"; done < "$SHADOW_DELETE"
fi
cd "$SHADOW_LOWER/$SHADOW_SUBDIR"
unset SHADOW_LOWER SHADOW_UPPER SHADOW_WORK SHADOW_DELETE SHADOW_SUBDIR SHADOW_MOUNT_STATUS SHADOW_CONTROL_DIR
setpriv_cmd="$SHADOW_SETPRIV"
unset SHADOW_SETPRIV
exec "$setpriv_cmd" --bounding-set=-all --inh-caps=-all --ambient-caps=-all --no-new-privs "$@" 2>&1
"#;

/// One hypothesis to run.
#[derive(Clone)]
pub struct Job {
    pub name: String,
    pub files: Vec<FileDelta>,
    pub argv: Vec<String>,
    pub env: Vec<(String, String)>,
    pub timeout: Duration,
    pub tail_limit: usize,
    pub workspace: PathBuf,
    /// Relative, `/`-separated directory inside the workspace to run in; empty for the root.
    pub subdir: String,
    pub shadow_root: PathBuf,
    pub fallback_shadow_root: Option<PathBuf>,
    pub ran_in_ram: Option<Arc<std::sync::atomic::AtomicBool>>,
    pub nonce: u64,
}

pub(crate) enum Ending {
    Exited(Option<std::process::ExitStatus>),
    TimedOut,
    Cancelled,
}
