[package]
name = "prod-code-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "prod-code-server"
path = "src/main.rs"

[dependencies]
prod-code-protocol = { path = "../prod-code-protocol" }
prod-code-engine-rust = { path = "../prod-code-engine-rust" }
prod-code-engine-go = { path = "../prod-code-engine-go" }
prod-code-engine-generic = { path = "../prod-code-engine-generic" }
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true


