[package]
name = "prod-code-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
lsp-types.workspace = true
tokio.workspace = true
tracing.workspace = true
bytes.workspace = true
tokio-util.workspace = true
url.workspace = true
socket2.workspace = true
hmac.workspace = true
sha2.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rustls-pki-types.workspace = true
rustls-pemfile.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true
