//! Shadow runs (roadmap 7.4): run a command once per hypothesis, a hypothesis being a set of
//! proposed file contents laid over the server workspace.
//!
//! On Linux with unprivileged user namespaces every hypothesis gets an overlay mount of the
//! workspace copy *at the workspace's own path*: cargo, go and the other build tools see the
//! same absolute paths, so their fingerprints and the warm `target/` stay valid, everything a
//! hypothesis writes lands in its own upper directory, and the workspace copy is never
//! modified. Hypotheses run in parallel, each in its own mount namespace that disappears with
//! its process tree. Without user namespaces (macOS, kernels that restrict them) hypotheses run
//! one after another in place and the touched files are restored afterwards.

use anyhow::{Context, Result};
use futures_util::{SinkExt, StreamExt};
use prod_code_protocol::{
    FileDelta, ProdCodeCodec, ShadowHypothesisResult, ShadowRunRequest, ShadowRunResponse,
    WireMessage,
};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};
use tokio::io::AsyncReadExt;
use tokio::net::TcpStream;
use tokio_util::codec::Framed;

/// Bytes of output kept per hypothesis unless the request says otherwise.
pub const DEFAULT_TAIL_BYTES: usize = 16 * 1024;
const DEFAULT_TIMEOUT_SECS: u64 = 3600;

/// The script every overlay hypothesis runs inside its own user + mount namespace: mount the
/// overlay over the workspace path, apply deletions, run the command with stderr merged.
const RUN_SCRIPT: &str = r#"#!/bin/sh
# Generated by prod-code for one hypothesis of a shadow run.
set -e
mount -t overlay overlay -o "lowerdir=$SHADOW_LOWER,upperdir=$SHADOW_UPPER,workdir=$SHADOW_WORK" "$SHADOW_LOWER"
if [ -s "$SHADOW_DELETE" ]; then
  while IFS= read -r p; do rm -rf "$SHADOW_LOWER/$p"; done < "$SHADOW_DELETE"
fi
cd "$SHADOW_LOWER/$SHADOW_SUBDIR"
exec "$@" 2>&1
"#;

/// Keeps the last `limit` bytes of a stream and counts everything that went through.
pub struct TailBuffer {
    limit: usize,
    buf: Vec<u8>,
    pub total: u64,
}

impl TailBuffer {
    pub fn new(limit: usize) -> Self {
        Self {
            limit: limit.max(1),
            buf: Vec::new(),
            total: 0,
        }
    }

    pub fn push(&mut self, data: &[u8]) {
        self.total += data.len() as u64;
        if data.len() >= self.limit {
            self.buf.clear();
            self.buf.extend_from_slice(&data[data.len() - self.limit..]);
            return;
        }
        self.buf.extend_from_slice(data);
        if self.buf.len() > self.limit {
            let cut = self.buf.len() - self.limit;
            self.buf.drain(..cut);
        }
    }

    pub fn bytes(&self) -> &[u8] {
        &self.buf
    }
}

/// `shadow` next to the workspace storage directory (same filesystem as the workspaces).
pub fn default_root(storage_root: &Path) -> PathBuf {
    storage_root
        .parent()
        .map(|p| p.join("shadow"))
        .unwrap_or_else(|| storage_root.join(".shadow"))
}

/// `None` when this node can run hypotheses as overlay shadows, otherwise why it cannot.
/// Probed once per process: a throw-away overlay mount inside a user namespace.
pub fn overlay_unavailable() -> Option<&'static str> {
    static PROBE: OnceLock<Option<String>> = OnceLock::new();
    PROBE.get_or_init(probe_overlay).as_deref()
}

fn probe_overlay() -> Option<String> {
    if !cfg!(target_os = "linux") {
        return Some("overlay shadows need Linux (user namespaces + overlayfs)".to_string());
    }
    let dir = std::env::temp_dir().join(format!("prod-code-shadow-probe-{}", std::process::id()));
    let (lower, upper, work, mnt) = (
        dir.join("lower"),
        dir.join("upper"),
        dir.join("work"),
        dir.join("mnt"),
    );
    let prepared = (|| -> std::io::Result<()> {
        for d in [&lower, &upper, &work, &mnt] {
            std::fs::create_dir_all(d)?;
        }
        std::fs::write(lower.join("probe"), "ok\n")
    })();
    if let Err(e) = prepared {
        return Some(format!("cannot prepare {}: {e}", dir.display()));
    }
    let script = format!(
        "mount -t overlay overlay -o lowerdir={l},upperdir={u},workdir={w} {m} && cat {m}/probe",
        l = lower.display(),
        u = upper.display(),
        w = work.display(),
        m = mnt.display()
    );
    let output = std::process::Command::new("unshare")
        .args(["-Urm", "--propagation", "private", "sh", "-c", &script])
        .output();
    let verdict = match output {
        Ok(o) if o.status.success() && o.stdout == b"ok\n" => None,
        Ok(o) => Some(format!(
            "unprivileged overlay mount failed: {}",
            String::from_utf8_lossy(&o.stderr).trim()
        )),
        Err(e) => Some(format!("cannot run unshare: {e}")),
    };
    remove_shadow_dir(&dir);
    verdict
}

/// Removes a shadow directory. The overlay work directory holds entries created by the
/// namespace's root with mode 000, which the gateway's own uid cannot delete directly, so
/// the removal is retried inside a user namespace.
pub fn remove_shadow_dir(dir: &Path) {
    if !dir.exists() {
        return;
    }
    if std::fs::remove_dir_all(dir).is_ok() {
        return;
    }
    let _ = std::process::Command::new("unshare")
        .args(["-Urm", "rm", "-rf"])
        .arg(dir)
        .status();
    if dir.exists() {
        tracing::warn!(dir = %dir.display(), "could not remove shadow directory");
    }
}

/// Removes every leftover hypothesis directory (from a crashed or killed gateway).
pub fn sweep(shadow_root: &Path) -> usize {
    let Ok(entries) = std::fs::read_dir(shadow_root) else {
        return 0;
    };
    let mut removed = 0;
    for entry in entries.flatten() {
        remove_shadow_dir(&entry.path());
        removed += 1;
    }
    removed
}

/// A relative path that stays inside the workspace, or `None`.
fn safe_relative(path: &str) -> Option<PathBuf> {
    let p = Path::new(path);
    if path.is_empty() || p.is_absolute() {
        return None;
    }
    let mut out = PathBuf::new();
    for component in p.components() {
        match component {
            std::path::Component::Normal(s) => out.push(s),
            std::path::Component::CurDir => {}
            _ => return None,
        }
    }
    (!out.as_os_str().is_empty()).then_some(out)
}

/// Writes the hypothesis's files into the overlay upper directory (they shadow the workspace
/// copy once mounted) and returns the paths to delete inside the mount.
fn stage_upper(upper: &Path, files: &[FileDelta]) -> Result<Vec<PathBuf>> {
    let mut deleted = Vec::new();
    for file in files {
        let rel = safe_relative(&file.relative_path)
            .with_context(|| format!("invalid path {:?}", file.relative_path))?;
        match &file.content {
            Some(bytes) => {
                let dest = upper.join(&rel);
                if let Some(parent) = dest.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&dest, bytes)?;
                #[cfg(unix)]
                if file.is_executable {
                    use std::os::unix::fs::PermissionsExt;
                    std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o755))?;
                }
            }
            None => deleted.push(rel),
        }
    }
    Ok(deleted)
}

fn dir_name(workspace: &Path, hypothesis: &str, nonce: u64) -> String {
    let ws = workspace
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "workspace".to_string());
    let safe: String = hypothesis
        .chars()
        .take(48)
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.') {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("{ws}--{safe}-{nonce:x}")
}

fn failed(name: &str, error: String) -> ShadowHypothesisResult {
    ShadowHypothesisResult {
        name: name.to_string(),
        exit_code: None,
        duration_ms: 0,
        timed_out: false,
        error: Some(error),
        output_tail: None,
        output_len: 0,
    }
}

/// One hypothesis to run.
pub struct Job {
    pub name: String,
    pub files: Vec<FileDelta>,
    pub argv: Vec<String>,
    pub env: Vec<(String, String)>,
    pub timeout: Duration,
    pub tail_limit: usize,
    pub workspace: PathBuf,
    /// Relative, `/`-separated directory inside the workspace to run in; empty for the root.
    pub subdir: String,
    pub shadow_root: PathBuf,
    pub nonce: u64,
}

enum Ending {
    Exited(Option<std::process::ExitStatus>),
    TimedOut,
    Cancelled,
}

/// Spawns `cmd`, keeps the tail of its output, enforces the timeout and the cancel signal.
async fn run_child(
    mut cmd: tokio::process::Command,
    job: &Job,
    mut cancel: tokio::sync::watch::Receiver<bool>,
) -> ShadowHypothesisResult {
    // The cluster's token is not the command's to see or send (#402).
    for var in prod_code_protocol::transport::AUTH_TOKEN_VARS {
        cmd.env_remove(var);
    }
    cmd.stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .kill_on_drop(true);
    // Own process group, so the timeout and a client disconnect take down the whole tree.
    #[cfg(unix)]
    cmd.process_group(0);
    let start = Instant::now();
    let mut child = match cmd.spawn() {
        Ok(child) => child,
        Err(e) => return failed(&job.name, format!("failed to start: {e}")),
    };
    let tail = Arc::new(Mutex::new(TailBuffer::new(job.tail_limit)));
    let mut readers = Vec::new();
    if let Some(out) = child.stdout.take() {
        readers.push(spawn_reader(out, Arc::clone(&tail)));
    }
    if let Some(err) = child.stderr.take() {
        readers.push(spawn_reader(err, Arc::clone(&tail)));
    }
    let ending = tokio::select! {
        status = child.wait() => Ending::Exited(status.ok()),
        _ = tokio::time::sleep(job.timeout) => Ending::TimedOut,
        _ = cancel.changed() => Ending::Cancelled,
    };
    let (status, timed_out, error) = match ending {
        Ending::Exited(status) => (status, false, None),
        Ending::TimedOut => {
            crate::kill_exec_tree(&mut child);
            (child.wait().await.ok(), true, None)
        }
        Ending::Cancelled => {
            crate::kill_exec_tree(&mut child);
            (
                child.wait().await.ok(),
                false,
                Some("cancelled: the client left".to_string()),
            )
        }
    };
    for reader in readers {
        let _ = reader.await;
    }
    let tail = tail.lock().unwrap_or_else(|e| e.into_inner());
    ShadowHypothesisResult {
        name: job.name.clone(),
        exit_code: status.and_then(|s| s.code()),
        duration_ms: start.elapsed().as_millis() as u64,
        timed_out,
        error,
        output_tail: Some(tail.bytes().to_vec()),
        output_len: tail.total,
    }
}

fn spawn_reader<R>(mut reader: R, tail: Arc<Mutex<TailBuffer>>) -> tokio::task::JoinHandle<()>
where
    R: tokio::io::AsyncRead + Unpin + Send + 'static,
{
    tokio::spawn(async move {
        let mut buf = vec![0u8; 16 * 1024];
        loop {
            match reader.read(&mut buf).await {
                Ok(0) | Err(_) => break,
                Ok(n) => tail
                    .lock()
                    .unwrap_or_else(|e| e.into_inner())
                    .push(&buf[..n]),
            }
        }
    })
}

/// Runs one hypothesis as an overlay shadow: its files go to a fresh upper directory, the
/// command runs in a user + mount namespace where the workspace path is the overlay.
pub async fn run_overlay(
    job: Job,
    cancel: tokio::sync::watch::Receiver<bool>,
) -> ShadowHypothesisResult {
    let dir = job
        .shadow_root
        .join(dir_name(&job.workspace, &job.name, job.nonce));
    let upper = dir.join("upper");
    let work = dir.join("work");
    let delete_list = dir.join("delete.txt");
    let script = dir.join("run.sh");
    let staged = (|| -> Result<()> {
        std::fs::create_dir_all(&upper)?;
        std::fs::create_dir_all(&work)?;
        let deleted = stage_upper(&upper, &job.files)?;
        let mut list = String::new();
        for path in deleted {
            list.push_str(&path.to_string_lossy());
            list.push('\n');
        }
        std::fs::write(&delete_list, list)?;
        std::fs::write(&script, RUN_SCRIPT)?;
        Ok(())
    })();
    if let Err(e) = staged {
        remove_shadow_dir(&dir);
        return failed(&job.name, format!("cannot stage hypothesis: {e:#}"));
    }
    let mut cmd = tokio::process::Command::new("unshare");
    cmd.args(["-Urm", "--propagation", "private", "sh"])
        .arg(&script)
        .args(&job.argv)
        .env("SHADOW_LOWER", &job.workspace)
        .env("SHADOW_UPPER", &upper)
        .env("SHADOW_WORK", &work)
        .env("SHADOW_DELETE", &delete_list)
        .env("SHADOW_SUBDIR", &job.subdir)
        .envs(job.env.iter().map(|(k, v)| (k.as_str(), v.as_str())))
        .current_dir(&job.workspace);
    let result = run_child(cmd, &job, cancel).await;
    // The upper directory can hold a whole incremental build; remove it off the response path.
    tokio::task::spawn_blocking(move || remove_shadow_dir(&dir));
    result
}

/// Runs one hypothesis in place: writes its files into the workspace copy, runs the command,
/// then restores every file whose content is still what the hypothesis wrote (a file someone
/// else changed meanwhile is left alone and logged).
pub async fn run_in_place(
    job: Job,
    cancel: tokio::sync::watch::Receiver<bool>,
) -> ShadowHypothesisResult {
    let mut originals: Vec<Touched> = Vec::new();
    for file in &job.files {
        let Some(rel) = safe_relative(&file.relative_path) else {
            restore(&originals);
            return failed(&job.name, format!("invalid path {:?}", file.relative_path));
        };
        let path = job.workspace.join(rel);
        let original = std::fs::read(&path).ok();
        let written = (|| -> std::io::Result<()> {
            match &file.content {
                Some(bytes) => {
                    if let Some(parent) = path.parent() {
                        std::fs::create_dir_all(parent)?;
                    }
                    std::fs::write(&path, bytes)
                }
                None => match std::fs::remove_file(&path) {
                    Ok(()) => Ok(()),
                    Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
                    Err(e) => Err(e),
                },
            }
        })();
        originals.push((path.clone(), original, file.content.clone()));
        if let Err(e) = written {
            restore(&originals);
            return failed(&job.name, format!("cannot write {}: {e}", path.display()));
        }
    }
    let mut cmd = tokio::process::Command::new("sh");
    cmd.args(["-c", "exec \"$@\" 2>&1", "sh"])
        .args(&job.argv)
        .envs(job.env.iter().map(|(k, v)| (k.as_str(), v.as_str())))
        .current_dir(job.workspace.join(&job.subdir));
    let result = run_child(cmd, &job, cancel).await;
    restore(&originals);
    result
}

/// A file the in-place mode touched: its path, its original content (None: did not exist)
/// and what the hypothesis wrote (None: deleted).
type Touched = (PathBuf, Option<Vec<u8>>, Option<Vec<u8>>);

fn restore(originals: &[Touched]) {
    for (path, original, written) in originals.iter().rev() {
        let current = std::fs::read(path).ok();
        if &current != written {
            tracing::warn!(
                path = %path.display(),
                "shadow run: file changed while the hypothesis ran; not restored"
            );
            continue;
        }
        let restored = match original {
            Some(bytes) => std::fs::write(path, bytes),
            None => match std::fs::remove_file(path) {
                Err(e) if e.kind() != std::io::ErrorKind::NotFound => Err(e),
                _ => Ok(()),
            },
        };
        if let Err(e) = restored {
            tracing::warn!(path = %path.display(), error = %e, "shadow run: could not restore file");
        }
    }
}

fn default_parallel() -> usize {
    std::thread::available_parallelism()
        .map(|n| (n.get() / 8).max(1))
        .unwrap_or(1)
}

/// Handles a `ShadowRunRequest` on a client connection: runs every hypothesis (in parallel as
/// overlays where the node supports them), answers pings meanwhile, kills everything if the
/// client leaves, and finishes with one `ShadowRunResponse`.
pub async fn run_shadow(
    state: &crate::ServerState,
    framed: &mut Framed<TcpStream, ProdCodeCodec>,
    req: ShadowRunRequest,
) -> Result<()> {
    let workspace = crate::workspace::server_workspace_path(
        &state.storage_root,
        &req.client_workspace_root,
        req.base_workspace_name.as_deref(),
    );
    let workspace_str = workspace.to_string_lossy().to_string();
    let refuse = |error: String| ShadowRunResponse {
        server_workspace_root: workspace_str.clone(),
        mode: String::new(),
        results: Vec::new(),
        error: Some(error),
    };
    let refusal = if !workspace.is_dir() {
        Some(format!(
            "workspace {workspace_str} is not synced to this gateway"
        ))
    } else if req.command.is_empty() {
        Some("empty command".to_string())
    } else if req.hypotheses.is_empty() {
        Some("no hypotheses".to_string())
    } else {
        let mut seen = std::collections::HashSet::new();
        req.hypotheses
            .iter()
            .find(|h| h.name.trim().is_empty() || !seen.insert(h.name.as_str()))
            .map(|h| format!("hypothesis name {:?} is empty or repeated", h.name))
    };
    if let Some(error) = refusal {
        framed
            .send(WireMessage::ShadowRunResponse(refuse(error)))
            .await?;
        return Ok(());
    }
    let subdir = match req.subdir.as_deref() {
        Some(sub)
            if !sub.is_empty()
                && !sub.starts_with('/')
                && !sub.split('/').any(|c| c == "..")
                && workspace.join(sub).is_dir() =>
        {
            sub.to_string()
        }
        _ => String::new(),
    };
    let timeout = Duration::from_secs(if req.timeout_secs == 0 {
        DEFAULT_TIMEOUT_SECS
    } else {
        req.timeout_secs
    });
    let tail_limit = if req.tail_bytes == 0 {
        DEFAULT_TAIL_BYTES
    } else {
        req.tail_bytes
    };
    let overlay_reason = tokio::task::spawn_blocking(overlay_unavailable)
        .await
        .unwrap_or(Some("overlay probe failed"));
    let overlay = overlay_reason.is_none();
    let mode = if overlay { "overlay" } else { "in-place" };
    let parallel = if !overlay {
        1
    } else if req.parallel == 0 {
        default_parallel()
    } else {
        req.parallel
    };
    if let Some(reason) = overlay_reason {
        tracing::info!(
            reason,
            "🌓 [SHADOW] overlay shadows unavailable; running in place"
        );
    }
    if overlay {
        std::fs::create_dir_all(&state.shadow_root)
            .with_context(|| format!("cannot create {}", state.shadow_root.display()))?;
    }
    let names: Vec<String> = req.hypotheses.iter().map(|h| h.name.clone()).collect();
    let count = names.len();
    tracing::info!(
        workspace = %workspace_str,
        command = %req.command.join(" "),
        hypotheses = count,
        mode,
        parallel,
        "🌓 [SHADOW] started"
    );
    let start = Instant::now();
    let (cancel_tx, cancel_rx) = tokio::sync::watch::channel(false);
    let semaphore = Arc::new(tokio::sync::Semaphore::new(parallel));
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    let mut handles = Vec::with_capacity(count);
    for hypothesis in req.hypotheses {
        let job = Job {
            name: hypothesis.name,
            files: hypothesis.files,
            argv: req.command.clone(),
            env: req.env.clone(),
            timeout,
            tail_limit,
            workspace: workspace.clone(),
            subdir: subdir.clone(),
            shadow_root: state.shadow_root.clone(),
            nonce,
        };
        let semaphore = Arc::clone(&semaphore);
        let cancel = cancel_rx.clone();
        handles.push(tokio::spawn(async move {
            let _permit = semaphore.acquire_owned().await;
            if *cancel.borrow() {
                return failed(&job.name, "cancelled: the client left".to_string());
            }
            if overlay {
                run_overlay(job, cancel).await
            } else {
                run_in_place(job, cancel).await
            }
        }));
    }
    let all = futures_util::future::join_all(handles);
    tokio::pin!(all);
    let joined = loop {
        tokio::select! {
            joined = &mut all => break joined,
            incoming = framed.next() => match incoming {
                Some(Ok(WireMessage::Ping)) => framed.send(WireMessage::Pong).await?,
                Some(Ok(WireMessage::Disconnect { .. })) | None => {
                    let _ = cancel_tx.send(true);
                    let _ = (&mut all).await;
                    tracing::info!(workspace = %workspace_str, "🌓 [SHADOW] client left; hypotheses killed");
                    return Ok(());
                }
                Some(Err(e)) => {
                    let _ = cancel_tx.send(true);
                    let _ = (&mut all).await;
                    return Err(e.into());
                }
                _ => {}
            }
        }
    };
    let results: Vec<ShadowHypothesisResult> = joined
        .into_iter()
        .zip(names.iter())
        .map(|(joined, name)| {
            joined.unwrap_or_else(|e| failed(name, format!("hypothesis task failed: {e}")))
        })
        .collect();
    for result in &results {
        let mut ev = crate::metrics::Event::blank("shadow");
        ev.agent = req
            .client_agent
            .clone()
            .unwrap_or_else(|| "unknown".to_string());
        ev.host = req
            .client_host
            .clone()
            .unwrap_or_else(|| "unknown".to_string());
        ev.workspace = workspace
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();
        ev.command = format!("{} [{}]", req.command.join(" "), result.name);
        ev.duration_ms = result.duration_ms;
        ev.exit_code = result.exit_code;
        ev.ok = result.exit_code == Some(0);
        ev.bytes = result.output_len;
        state.metrics.record(ev);
    }
    tracing::info!(
        workspace = %workspace_str,
        hypotheses = count,
        passed = results.iter().filter(|r| r.exit_code == Some(0)).count(),
        duration_ms = start.elapsed().as_millis() as u64,
        "🌓 [SHADOW] finished"
    );
    framed
        .send(WireMessage::ShadowRunResponse(ShadowRunResponse {
            server_workspace_root: workspace_str,
            mode: mode.to_string(),
            results,
            error: None,
        }))
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn job(
        workspace: &Path,
        shadow_root: &Path,
        name: &str,
        files: Vec<FileDelta>,
        argv: &[&str],
    ) -> Job {
        Job {
            name: name.to_string(),
            files,
            argv: argv.iter().map(|s| s.to_string()).collect(),
            env: Vec::new(),
            timeout: Duration::from_secs(30),
            tail_limit: 4096,
            workspace: workspace.to_path_buf(),
            subdir: String::new(),
            shadow_root: shadow_root.to_path_buf(),
            nonce: 7,
        }
    }

    fn delta(path: &str, content: Option<&str>) -> FileDelta {
        FileDelta {
            relative_path: path.to_string(),
            content: content.map(|c| c.as_bytes().to_vec()),
            is_executable: false,
        }
    }

    fn output(result: &ShadowHypothesisResult) -> String {
        String::from_utf8_lossy(result.output_tail.as_deref().unwrap_or_default()).into_owned()
    }

    #[test]
    fn tail_buffer_keeps_only_the_end_and_counts_everything() {
        let mut tail = TailBuffer::new(5);
        tail.push(b"abc");
        tail.push(b"defgh");
        tail.push(b"ij");
        assert_eq!(tail.bytes(), b"fghij");
        assert_eq!(tail.total, 10);
        tail.push(b"0123456789");
        assert_eq!(tail.bytes(), b"56789");
    }

    #[test]
    fn safe_relative_rejects_absolute_and_parent_paths() {
        assert_eq!(
            safe_relative("src/lib.rs"),
            Some(PathBuf::from("src/lib.rs"))
        );
        assert_eq!(
            safe_relative("./src/lib.rs"),
            Some(PathBuf::from("src/lib.rs"))
        );
        assert_eq!(safe_relative("/etc/passwd"), None);
        assert_eq!(safe_relative("../x"), None);
        assert_eq!(safe_relative("src/../../x"), None);
        assert_eq!(safe_relative(""), None);
    }

    #[test]
    fn stage_upper_writes_files_and_lists_deletions() {
        let upper = tempfile::tempdir().unwrap();
        let deleted = stage_upper(
            upper.path(),
            &[
                delta("crates/x/src/lib.rs", Some("pub fn x() {}\n")),
                delta("old.rs", None),
            ],
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(upper.path().join("crates/x/src/lib.rs")).unwrap(),
            "pub fn x() {}\n"
        );
        assert_eq!(deleted, vec![PathBuf::from("old.rs")]);
        assert!(stage_upper(upper.path(), &[delta("../escape", Some(""))]).is_err());
    }

    #[test]
    fn dir_names_are_filesystem_safe() {
        let name = dir_name(Path::new("/srv/ws/repo--wt-1"), "fix: use/slice", 255);
        assert_eq!(name, "repo--wt-1--fix__use_slice-ff");
    }

    #[tokio::test]
    async fn in_place_hypotheses_restore_the_workspace() {
        let ws = tempfile::tempdir().unwrap();
        std::fs::write(ws.path().join("a.txt"), "base\n").unwrap();
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let shadow = tempfile::tempdir().unwrap();
        let argv = ["sh", "-c", "cat a.txt 2>&1; ls"];
        let one = run_in_place(
            job(
                ws.path(),
                shadow.path(),
                "one",
                vec![delta("a.txt", Some("one\n")), delta("b.txt", Some("new\n"))],
                &argv,
            ),
            rx.clone(),
        )
        .await;
        assert_eq!(one.exit_code, Some(0), "{:?}", one.error);
        assert!(output(&one).contains("one") && output(&one).contains("b.txt"));
        let two = run_in_place(
            job(
                ws.path(),
                shadow.path(),
                "two",
                vec![delta("a.txt", None)],
                &argv,
            ),
            rx,
        )
        .await;
        assert_eq!(two.exit_code, Some(0));
        assert!(!output(&two).contains("base"));
        assert_eq!(
            std::fs::read_to_string(ws.path().join("a.txt")).unwrap(),
            "base\n"
        );
        assert!(!ws.path().join("b.txt").exists());
    }

    /// Needs unprivileged user namespaces + overlayfs (Linux); skipped elsewhere.
    #[tokio::test]
    async fn overlay_hypotheses_run_in_parallel_and_leave_the_workspace_untouched() {
        if let Some(reason) = overlay_unavailable() {
            eprintln!("skipped: {reason}");
            return;
        }
        let ws = tempfile::tempdir().unwrap();
        std::fs::write(ws.path().join("a.txt"), "base\n").unwrap();
        let shadow = tempfile::tempdir().unwrap();
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let argv = ["sh", "-c", "cat a.txt 2>&1; ls; echo made > made.txt"];
        let one = run_overlay(
            job(
                ws.path(),
                shadow.path(),
                "one",
                vec![delta("a.txt", Some("one\n")), delta("b.txt", Some("new\n"))],
                &argv,
            ),
            rx.clone(),
        );
        let two = run_overlay(
            job(
                ws.path(),
                shadow.path(),
                "two",
                vec![delta("a.txt", None)],
                &argv,
            ),
            rx,
        );
        let (one, two) = tokio::join!(one, two);
        assert_eq!(one.exit_code, Some(0), "{:?} {}", one.error, output(&one));
        assert!(output(&one).contains("one") && output(&one).contains("b.txt"));
        assert_eq!(two.exit_code, Some(0), "{:?} {}", two.error, output(&two));
        assert!(!output(&two).contains("base") && !output(&two).contains("a.txt\n"));
        assert_eq!(
            std::fs::read_to_string(ws.path().join("a.txt")).unwrap(),
            "base\n"
        );
        assert!(!ws.path().join("b.txt").exists());
        assert!(!ws.path().join("made.txt").exists());
        // The upper directories are removed after each hypothesis.
        tokio::time::sleep(Duration::from_millis(300)).await;
        assert_eq!(std::fs::read_dir(shadow.path()).unwrap().count(), 0);
    }
}
