//! Shadow runs (roadmap 7.4): run a command once per hypothesis, a hypothesis being a set of
//! proposed file contents laid over the server workspace.
//!
//! On Linux with unprivileged user namespaces every hypothesis gets an overlay mount of the
//! workspace copy *at the workspace's own path*: cargo, go and the other build tools see the
//! same absolute paths, so their fingerprints and the warm `target/` stay valid, everything a
//! hypothesis writes lands in its own upper directory, and the workspace copy is never
//! modified. Hypotheses run in parallel, each in its own mount namespace that disappears with
//! its process tree. Without user namespaces (macOS, kernels that restrict them) hypotheses run
//! one after another in place and the touched files are restored afterwards.

use anyhow::{Context, Result};
use futures_util::{SinkExt, StreamExt};
use prod_code_protocol::{
    FileDelta, ProdCodeCodec, ShadowHypothesisResult, ShadowRunRequest, ShadowRunResponse,
    WireMessage,
};
use std::ffi::OsString;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};
use tokio::io::AsyncReadExt;
use tokio::net::TcpStream;
use tokio_util::codec::Framed;

/// Bytes of output kept per hypothesis unless the request says otherwise.
pub const DEFAULT_TAIL_BYTES: usize = 16 * 1024;
const DEFAULT_TIMEOUT_SECS: u64 = 3600;

/// The script every overlay hypothesis runs inside its own user + mount namespace: mount the
/// overlay over the workspace path, apply deletions, run the command with stderr merged.
const RUN_SCRIPT: &str = r#"#!/bin/sh
# Generated by prod-code for one hypothesis of a shadow run.
set -e
mount -t overlay overlay -o "lowerdir=$SHADOW_LOWER,upperdir=$SHADOW_UPPER,workdir=$SHADOW_WORK" "$SHADOW_LOWER"
if [ -s "$SHADOW_DELETE" ]; then
  while IFS= read -r p; do rm -rf "$SHADOW_LOWER/$p"; done < "$SHADOW_DELETE"
fi
cd "$SHADOW_LOWER/$SHADOW_SUBDIR"
exec "$@" 2>&1
"#;

/// Keeps the last `limit` bytes of a stream and counts everything that went through.
pub struct TailBuffer {
    limit: usize,
    buf: Vec<u8>,
    pub total: u64,
}

impl TailBuffer {
    pub fn new(limit: usize) -> Self {
        Self {
            limit: limit.max(1),
            buf: Vec::new(),
            total: 0,
        }
    }

    pub fn push(&mut self, data: &[u8]) {
        self.total += data.len() as u64;
        if data.len() >= self.limit {
            self.buf.clear();
            self.buf.extend_from_slice(&data[data.len() - self.limit..]);
            return;
        }
        self.buf.extend_from_slice(data);
        if self.buf.len() > self.limit {
            let cut = self.buf.len() - self.limit;
            self.buf.drain(..cut);
        }
    }

    pub fn bytes(&self) -> &[u8] {
        &self.buf
    }
}

/// `shadow` next to the workspace storage directory (same filesystem as the workspaces).
pub fn default_root(storage_root: &Path) -> PathBuf {
    storage_root
        .parent()
        .map(|p| p.join("shadow"))
        .unwrap_or_else(|| storage_root.join(".shadow"))
}

/// `None` when this node can run hypotheses as overlay shadows, otherwise why it cannot.
/// Probed once per process: a throw-away overlay mount inside a user namespace.
pub fn overlay_unavailable() -> Option<&'static str> {
    static PROBE: OnceLock<Option<String>> = OnceLock::new();
    PROBE.get_or_init(probe_overlay).as_deref()
}

fn probe_overlay() -> Option<String> {
    if !cfg!(target_os = "linux") {
        return Some("overlay shadows need Linux (user namespaces + overlayfs)".to_string());
    }
    let dir = std::env::temp_dir().join(format!("prod-code-shadow-probe-{}", std::process::id()));
    let (lower, upper, work, mnt) = (
        dir.join("lower"),
        dir.join("upper"),
        dir.join("work"),
        dir.join("mnt"),
    );
    let prepared = (|| -> std::io::Result<()> {
        for d in [&lower, &upper, &work, &mnt] {
            std::fs::create_dir_all(d)?;
        }
        std::fs::write(lower.join("probe"), "ok\n")
    })();
    if let Err(e) = prepared {
        return Some(format!("cannot prepare {}: {e}", dir.display()));
    }
    let script = format!(
        "mount -t overlay overlay -o lowerdir={l},upperdir={u},workdir={w} {m} && cat {m}/probe",
        l = lower.display(),
        u = upper.display(),
        w = work.display(),
        m = mnt.display()
    );
    let output = std::process::Command::new("unshare")
        .args(["-Urm", "--propagation", "private", "sh", "-c", &script])
        .output();
    let verdict = match output {
        Ok(o) if o.status.success() && o.stdout == b"ok\n" => None,
        Ok(o) => Some(format!(
            "unprivileged overlay mount failed: {}",
            String::from_utf8_lossy(&o.stderr).trim()
        )),
        Err(e) => Some(format!("cannot run unshare: {e}")),
    };
    remove_shadow_dir(&dir);
    verdict
}

/// Removes a shadow directory. The overlay work directory holds entries created by the
/// namespace's root with mode 000, which the gateway's own uid cannot delete directly, so
/// the removal is retried inside a user namespace.
pub fn remove_shadow_dir(dir: &Path) {
    if !dir.exists() {
        return;
    }
    if std::fs::remove_dir_all(dir).is_ok() {
        return;
    }
    let _ = std::process::Command::new("unshare")
        .args(["-Urm", "rm", "-rf"])
        .arg(dir)
        .status();
    if dir.exists() {
        tracing::warn!(dir = %dir.display(), "could not remove shadow directory");
    }
}

/// Removes every leftover hypothesis directory (from a crashed or killed gateway).
pub fn sweep(shadow_root: &Path) -> usize {
    let Ok(entries) = std::fs::read_dir(shadow_root) else {
        return 0;
    };
    let mut removed = 0;
    for entry in entries.flatten() {
        remove_shadow_dir(&entry.path());
        removed += 1;
    }
    removed
}

/// A relative path that stays inside the workspace, or `None`.
fn safe_relative(path: &str) -> Option<PathBuf> {
    let p = Path::new(path);
    if path.is_empty() || p.is_absolute() {
        return None;
    }
    let mut out = PathBuf::new();
    for component in p.components() {
        match component {
            std::path::Component::Normal(s) => out.push(s),
            std::path::Component::CurDir => {}
            _ => return None,
        }
    }
    (!out.as_os_str().is_empty()).then_some(out)
}

/// Writes the hypothesis's files into the overlay upper directory (they shadow the workspace
/// copy once mounted) and returns the paths to delete inside the mount.
fn stage_upper(upper: &Path, files: &[FileDelta]) -> Result<Vec<PathBuf>> {
    let mut deleted = Vec::new();
    for file in files {
        let rel = safe_relative(&file.relative_path)
            .with_context(|| format!("invalid path {:?}", file.relative_path))?;
        match &file.content {
            Some(bytes) => {
                let dest = upper.join(&rel);
                if let Some(parent) = dest.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&dest, bytes)?;
                #[cfg(unix)]
                if file.is_executable {
                    use std::os::unix::fs::PermissionsExt;
                    std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o755))?;
                }
            }
            None => deleted.push(rel),
        }
    }
    Ok(deleted)
}

fn dir_name(workspace: &Path, hypothesis: &str, nonce: u64) -> String {
    let ws = workspace
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "workspace".to_string());
    let safe: String = hypothesis
        .chars()
        .take(48)
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.') {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("{ws}--{safe}-{nonce:x}")
}

fn failed(name: &str, error: String) -> ShadowHypothesisResult {
    ShadowHypothesisResult {
        name: name.to_string(),
        exit_code: None,
        duration_ms: 0,
        timed_out: false,
        error: Some(error),
        output_tail: None,
        output_len: 0,
    }
}

/// One hypothesis to run.
pub struct Job {
    pub name: String,
    pub files: Vec<FileDelta>,
    pub argv: Vec<String>,
    pub env: Vec<(String, String)>,
    pub timeout: Duration,
    pub tail_limit: usize,
    pub workspace: PathBuf,
    /// Relative, `/`-separated directory inside the workspace to run in; empty for the root.
    pub subdir: String,
    pub shadow_root: PathBuf,
    pub nonce: u64,
}

enum Ending {
    Exited(Option<std::process::ExitStatus>),
    TimedOut,
    Cancelled,
}

/// Spawns `cmd`, keeps the tail of its output, enforces the timeout and the cancel signal.
async fn run_child(
    mut cmd: tokio::process::Command,
    job: &Job,
    mut cancel: tokio::sync::watch::Receiver<bool>,
) -> ShadowHypothesisResult {
    // The cluster's token is not the command's to see or send (#402).
    for var in prod_code_protocol::transport::AUTH_TOKEN_VARS {
        cmd.env_remove(var);
    }
    cmd.stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .kill_on_drop(true);
    // Own process group, so the timeout and a client disconnect take down the whole tree.
    #[cfg(unix)]
    cmd.process_group(0);
    let start = Instant::now();
    let mut child = match cmd.spawn() {
        Ok(child) => child,
        Err(e) => return failed(&job.name, format!("failed to start: {e}")),
    };
    let tail = Arc::new(Mutex::new(TailBuffer::new(job.tail_limit)));
    let mut readers = Vec::new();
    if let Some(out) = child.stdout.take() {
        readers.push(spawn_reader(out, Arc::clone(&tail)));
    }
    if let Some(err) = child.stderr.take() {
        readers.push(spawn_reader(err, Arc::clone(&tail)));
    }
    let ending = tokio::select! {
        status = child.wait() => Ending::Exited(status.ok()),
        _ = tokio::time::sleep(job.timeout) => Ending::TimedOut,
        _ = cancel.changed() => Ending::Cancelled,
    };
    let (status, timed_out, error) = match ending {
        Ending::Exited(status) => (status, false, None),
        Ending::TimedOut => {
            crate::kill_exec_tree(&mut child);
            (child.wait().await.ok(), true, None)
        }
        Ending::Cancelled => {
            crate::kill_exec_tree(&mut child);
            (
                child.wait().await.ok(),
                false,
                Some("cancelled: the client left".to_string()),
            )
        }
    };
    for reader in readers {
        let _ = reader.await;
    }
    let tail = tail.lock().unwrap_or_else(|e| e.into_inner());
    ShadowHypothesisResult {
        name: job.name.clone(),
        exit_code: status.and_then(|s| s.code()),
        duration_ms: start.elapsed().as_millis() as u64,
        timed_out,
        error,
        output_tail: Some(tail.bytes().to_vec()),
        output_len: tail.total,
    }
}

fn spawn_reader<R>(mut reader: R, tail: Arc<Mutex<TailBuffer>>) -> tokio::task::JoinHandle<()>
where
    R: tokio::io::AsyncRead + Unpin + Send + 'static,
{
    tokio::spawn(async move {
        let mut buf = vec![0u8; 16 * 1024];
        loop {
            match reader.read(&mut buf).await {
                Ok(0) | Err(_) => break,
                Ok(n) => tail
                    .lock()
                    .unwrap_or_else(|e| e.into_inner())
                    .push(&buf[..n]),
            }
        }
    })
}

/// Why an overlay hypothesis must not run, or `None`. An sccache daemon started outside the
/// hypothesis's mount namespace compiles against the real workspace, so sccache has to stay in
/// client-side mode, where the wrapper process inside the namespace compiles (#426).
fn check_isolation_conflicts(job: &Job) -> Option<String> {
    let var = |key: &str| effective_var(&job.env, key);
    sccache_client_side(&var, &job.workspace, &job.files)
        .err()
        .map(|why| format!("cannot run an overlay shadow: {why}"))
}

/// A variable as the overlay command sees it: the request's env wins over the gateway's, and
/// `SCCACHE_CLIENT_SIDE` is the `1` that `run_overlay` sets unless the request overrides it.
fn effective_var(env: &[(String, String)], key: &str) -> Option<OsString> {
    if let Some((_, value)) = env.iter().rev().find(|(k, _)| k == key) {
        return Some(value.into());
    }
    if key == "SCCACHE_CLIENT_SIDE" {
        return Some("1".into());
    }
    std::env::var_os(key)
}

/// `Ok` when an sccache client started with these variables compiles in client-side mode,
/// resolved as sccache 0.17 `Config::load` does: a non-empty `SCCACHE_CLIENT_SIDE` wins over
/// the config file's `client_side_mode`, and the mode is off while `SCCACHE_LOG` is set or the
/// config file names `dist.scheduler_url`. Distributed compilation is configured only in that
/// file, never through the environment.
fn sccache_client_side(
    var: &dyn Fn(&str) -> Option<OsString>,
    workspace: &Path,
    files: &[FileDelta],
) -> std::result::Result<(), String> {
    // sccache reads the variable with `env::var(..).ok()` and ignores an empty value.
    let from_env = match var("SCCACHE_CLIENT_SIDE")
        .and_then(|v| v.into_string().ok())
        .filter(|v| !v.is_empty())
    {
        None => None,
        Some(v) => match v.to_lowercase().as_str() {
            "true" | "on" | "1" => Some(true),
            "false" | "off" | "0" => {
                return Err(
                    "SCCACHE_CLIENT_SIDE turns sccache's client-side mode off, and \
                            sccache would compile in its daemon outside the hypothesis's \
                            mount namespace"
                        .to_string(),
                );
            }
            _ => {
                return Err(
                    "SCCACHE_CLIENT_SIDE is not one of true, on, 1 (sccache rejects \
                            any value other than true, on, 1, false, off, 0)"
                        .to_string(),
                );
            }
        },
    };
    if var("SCCACHE_LOG").is_some() {
        return Err(
            "SCCACHE_LOG is set, and sccache turns client-side mode off while it logs; \
                    unset it for shadow runs"
                .to_string(),
        );
    }
    let path = sccache_config_path(var)?;
    let (scheduler, from_file) = match sccache_config_content(&path, workspace, files)? {
        Some(bytes) => parse_sccache_config(&path, &bytes)?,
        None => (false, false),
    };
    if scheduler {
        return Err(format!(
            "the sccache config {} sets dist.scheduler_url; distributed compilation runs \
             outside the hypothesis's mount namespace and is not supported in shadow runs",
            path.display()
        ));
    }
    if !from_env.unwrap_or(from_file) {
        return Err(format!(
            "sccache's client-side mode is off: SCCACHE_CLIENT_SIDE is empty and the config {} \
             does not set client_side_mode = true",
            path.display()
        ));
    }
    Ok(())
}

/// The config file sccache reads: `SCCACHE_CONF`, otherwise the Linux config directory of
/// the `directories` crate (`$XDG_CONFIG_HOME` when absolute, else `$HOME/.config`).
fn sccache_config_path(
    var: &dyn Fn(&str) -> Option<OsString>,
) -> std::result::Result<PathBuf, String> {
    if let Some(conf) = var("SCCACHE_CONF") {
        let path = PathBuf::from(conf);
        if !path.is_absolute() {
            return Err(
                "SCCACHE_CONF must be an absolute path in shadow runs: sccache \
                        resolves a relative one against each compiler's working directory"
                    .to_string(),
            );
        }
        return Ok(path);
    }
    let config_home = var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .filter(|p| p.is_absolute())
        .or_else(|| {
            var("HOME")
                .filter(|h| !h.is_empty())
                .map(|h| PathBuf::from(h).join(".config"))
        })
        .ok_or(
            "cannot locate the sccache config: none of SCCACHE_CONF, XDG_CONFIG_HOME and \
                HOME is set",
        )?;
    Ok(config_home.join("sccache").join("config"))
}

/// The config file's bytes as the hypothesis sees them (`None`: no file). The path is followed
/// through `..` and symlinks in the hypothesis's own view, so an alias such as
/// `ws/ci/../sccache.toml` or a symlink from outside into the workspace reads the proposed file
/// the overlay command would read (#426).
fn sccache_config_content(
    path: &Path,
    workspace: &Path,
    files: &[FileDelta],
) -> std::result::Result<Option<Vec<u8>>, String> {
    let unreadable =
        |why: &str| format!("cannot read the sccache config {}: {why}", path.display());
    let view = HypothesisView::new(workspace, files);
    let (physical, node) = view.resolve(path, true).map_err(|why| unreadable(&why))?;
    match node {
        Node::Missing => Ok(None),
        Node::Proposed(bytes) => Ok(Some(bytes.to_vec())),
        Node::Disk => match std::fs::read(&physical) {
            Ok(bytes) => Ok(Some(bytes)),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(unreadable(&e.kind().to_string())),
        },
        Node::Dir { .. } => Err(unreadable("is a directory")),
        Node::Link(_) => Err(unreadable("is a symbolic link")),
    }
}

/// Symlinks followed while resolving one path before giving up, as Linux does (`ELOOP`).
const MAX_SYMLINKS: usize = 40;

/// What a path is in the hypothesis's mount namespace.
enum Node<'a> {
    Missing,
    /// `upper_only`: a staged directory that hides a non-directory below it, so the workspace
    /// copy contributes nothing under it.
    Dir {
        upper_only: bool,
    },
    Link(PathBuf),
    Proposed(&'a [u8]),
    Disk,
}

enum Step {
    Root,
    Up,
    Name(OsString),
}

fn steps(path: &Path) -> Vec<Step> {
    path.components()
        .filter_map(|c| match c {
            std::path::Component::Prefix(_) | std::path::Component::RootDir => Some(Step::Root),
            std::path::Component::CurDir => None,
            std::path::Component::ParentDir => Some(Step::Up),
            std::path::Component::Normal(name) => Some(Step::Name(name.to_os_string())),
        })
        .collect()
}

/// The filesystem as an overlay hypothesis sees it: at the workspace path, the proposed files
/// (staged as regular files, so one replaces a symlink rather than writing through it) over the
/// workspace copy, minus the deletions the run script applies after mounting; everywhere else,
/// the gateway's own filesystem.
struct HypothesisView<'a> {
    /// Where the overlay is mounted: the workspace path with its symlinks resolved.
    workspace: PathBuf,
    proposed: Vec<(PathBuf, &'a [u8])>,
    /// Physical paths `rm -rf` removes, in the view without symlinks.
    deleted: Vec<PathBuf>,
}

impl<'a> HypothesisView<'a> {
    fn new(workspace: &Path, files: &'a [FileDelta]) -> Self {
        let workspace =
            std::fs::canonicalize(workspace).unwrap_or_else(|_| workspace.to_path_buf());
        let mut view = Self {
            workspace,
            proposed: Vec::new(),
            deleted: Vec::new(),
        };
        let mut deletions = Vec::new();
        for file in files {
            // An invalid path fails staging, so the command never runs.
            let Some(rel) = safe_relative(&file.relative_path) else {
                continue;
            };
            match &file.content {
                Some(bytes) => view.proposed.push((rel, bytes.as_slice())),
                None => deletions.push(rel),
            }
        }
        // Each `rm -rf` follows the directories of its path in the mount as the earlier ones
        // left it, and removes the last component itself, not what a symlink there points to.
        for rel in deletions {
            let path = view.workspace.join(rel);
            match view.resolve(&path, false) {
                Ok((_, Node::Missing)) | Err(_) => {}
                Ok((target, _)) => view.deleted.push(target),
            }
        }
        view
    }

    /// Follows an absolute path component by component as the kernel does inside the
    /// namespace, through `..` and symlinks (the last one only with `follow_last`), and returns
    /// the physical path reached and what is there.
    fn resolve(
        &self,
        path: &Path,
        follow_last: bool,
    ) -> std::result::Result<(PathBuf, Node<'a>), String> {
        if !path.is_absolute() {
            return Err("it is not an absolute path".to_string());
        }
        let mut pending = steps(path);
        pending.reverse();
        let mut cur = PathBuf::from("/");
        // One entry per component of `cur`: whether it is an upper-only directory.
        let mut upper_only: Vec<bool> = Vec::new();
        let mut links = 0;
        while let Some(step) = pending.pop() {
            let name = match step {
                Step::Root => {
                    cur = PathBuf::from("/");
                    upper_only.clear();
                    continue;
                }
                Step::Up => {
                    if cur.pop() {
                        upper_only.pop();
                    }
                    continue;
                }
                Step::Name(name) => name,
            };
            let next = cur.join(&name);
            let last = pending.is_empty();
            match self.node(&next, upper_only.last().copied().unwrap_or(false))? {
                Node::Dir { upper_only: hidden } => {
                    cur = next;
                    upper_only.push(hidden);
                }
                Node::Link(target) if follow_last || !last => {
                    links += 1;
                    if links > MAX_SYMLINKS {
                        return Err("too many levels of symbolic links".to_string());
                    }
                    pending.extend(steps(&target).into_iter().rev());
                }
                node if last => return Ok((next, node)),
                Node::Missing => return Ok((next, Node::Missing)),
                _ => return Err("a component of the path is not a directory".to_string()),
            }
        }
        let hidden = upper_only.last().copied().unwrap_or(false);
        Ok((cur, Node::Dir { upper_only: hidden }))
    }

    /// What `path`, whose parent is a directory of the view without symlinks, is. `upper_only`
    /// says the parent is a staged directory that hides the workspace copy.
    fn node(&self, path: &Path, upper_only: bool) -> std::result::Result<Node<'a>, String> {
        if self.deleted.iter().any(|d| path.starts_with(d)) {
            return Ok(Node::Missing);
        }
        if let Ok(rel) = path.strip_prefix(&self.workspace) {
            // Staged in order, so the last copy of a path wins.
            if let Some((_, bytes)) = self.proposed.iter().rev().find(|(p, _)| p == rel) {
                return Ok(Node::Proposed(bytes));
            }
            if self.proposed.iter().any(|(p, _)| p.starts_with(rel)) {
                // A staged directory merges with a directory below it and hides anything else.
                let merged =
                    !upper_only && std::fs::symlink_metadata(path).is_ok_and(|m| m.is_dir());
                return Ok(Node::Dir {
                    upper_only: !merged,
                });
            }
            if upper_only {
                return Ok(Node::Missing);
            }
        }
        match std::fs::symlink_metadata(path) {
            Ok(m) if m.file_type().is_symlink() => std::fs::read_link(path)
                .map(Node::Link)
                .map_err(|e| e.kind().to_string()),
            Ok(m) if m.is_dir() => Ok(Node::Dir { upper_only: false }),
            Ok(_) => Ok(Node::Disk),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Node::Missing),
            Err(e) => Err(e.kind().to_string()),
        }
    }
}

/// `(dist.scheduler_url is set, client_side_mode)` from a config file: JSON when its extension
/// is `json`, TOML otherwise, as sccache decides. Parser messages are not passed on because
/// they quote the file, which can hold cache credentials.
fn parse_sccache_config(path: &Path, bytes: &[u8]) -> std::result::Result<(bool, bool), String> {
    let invalid = |what: &str| format!("the sccache config {} {what}", path.display());
    let text = std::str::from_utf8(bytes).map_err(|_| invalid("is not UTF-8 text"))?;
    let value: serde_json::Value = if path.extension().is_some_and(|e| e == "json") {
        serde_json::from_str(text).map_err(|_| invalid("is not valid JSON"))?
    } else {
        toml::from_str::<toml::Table>(text)
            .ok()
            .and_then(|table| serde_json::to_value(table).ok())
            .ok_or_else(|| invalid("is not valid TOML"))?
    };
    let root = value.as_object().ok_or_else(|| invalid("is not a table"))?;
    let scheduler = match root.get("dist") {
        None => false,
        Some(serde_json::Value::Object(dist)) => {
            dist.get("scheduler_url").is_some_and(|url| !url.is_null())
        }
        Some(_) => return Err(invalid("has a `dist` that is not a table")),
    };
    let client_side = match root.get("client_side_mode") {
        None => false,
        Some(serde_json::Value::Bool(on)) => *on,
        Some(_) => return Err(invalid("has a `client_side_mode` that is not a boolean")),
    };
    Ok((scheduler, client_side))
}

/// Runs one hypothesis as an overlay shadow: its files go to a fresh upper directory, the
/// command runs in a user + mount namespace where the workspace path is the overlay.
pub async fn run_overlay(
    job: Job,
    cancel: tokio::sync::watch::Receiver<bool>,
) -> ShadowHypothesisResult {
    if let Some(err) = check_isolation_conflicts(&job) {
        tracing::info!(hypothesis = %job.name, reason = %err, "🌓 [SHADOW] hypothesis refused");
        return failed(&job.name, err);
    }
    let dir = job
        .shadow_root
        .join(dir_name(&job.workspace, &job.name, job.nonce));
    let upper = dir.join("upper");
    let work = dir.join("work");
    let delete_list = dir.join("delete.txt");
    let script = dir.join("run.sh");
    let staged = (|| -> Result<()> {
        std::fs::create_dir_all(&upper)?;
        std::fs::create_dir_all(&work)?;
        let deleted = stage_upper(&upper, &job.files)?;
        let mut list = String::new();
        for path in deleted {
            list.push_str(&path.to_string_lossy());
            list.push('\n');
        }
        std::fs::write(&delete_list, list)?;
        std::fs::write(&script, RUN_SCRIPT)?;
        Ok(())
    })();
    if let Err(e) = staged {
        remove_shadow_dir(&dir);
        return failed(&job.name, format!("cannot stage hypothesis: {e:#}"));
    }
    let mut cmd = tokio::process::Command::new("unshare");
    cmd.args(["-Urm", "--propagation", "private", "sh"])
        .arg(&script)
        .args(&job.argv)
        .env("SHADOW_LOWER", &job.workspace)
        .env("SHADOW_UPPER", &upper)
        .env("SHADOW_WORK", &work)
        .env("SHADOW_DELETE", &delete_list)
        .env("SHADOW_SUBDIR", &job.subdir)
        // Ensure sccache compiles in the client process inside the mount namespace (#426).
        .env("SCCACHE_CLIENT_SIDE", "1")
        .envs(job.env.iter().map(|(k, v)| (k.as_str(), v.as_str())))
        .current_dir(&job.workspace);
    let result = run_child(cmd, &job, cancel).await;
    // The upper directory can hold a whole incremental build; remove it off the response path.
    tokio::task::spawn_blocking(move || remove_shadow_dir(&dir));
    result
}

/// Runs one hypothesis in place: writes its files into the workspace copy, runs the command,
/// then restores every file whose content is still what the hypothesis wrote (a file someone
/// else changed meanwhile is left alone and logged).
pub async fn run_in_place(
    job: Job,
    cancel: tokio::sync::watch::Receiver<bool>,
) -> ShadowHypothesisResult {
    let mut originals: Vec<Touched> = Vec::new();
    for file in &job.files {
        let Some(rel) = safe_relative(&file.relative_path) else {
            restore(&originals);
            return failed(&job.name, format!("invalid path {:?}", file.relative_path));
        };
        let path = job.workspace.join(rel);
        let original = std::fs::read(&path).ok();
        let written = (|| -> std::io::Result<()> {
            match &file.content {
                Some(bytes) => {
                    if let Some(parent) = path.parent() {
                        std::fs::create_dir_all(parent)?;
                    }
                    std::fs::write(&path, bytes)
                }
                None => match std::fs::remove_file(&path) {
                    Ok(()) => Ok(()),
                    Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
                    Err(e) => Err(e),
                },
            }
        })();
        originals.push((path.clone(), original, file.content.clone()));
        if let Err(e) = written {
            restore(&originals);
            return failed(&job.name, format!("cannot write {}: {e}", path.display()));
        }
    }
    let mut cmd = tokio::process::Command::new("sh");
    cmd.args(["-c", "exec \"$@\" 2>&1", "sh"])
        .args(&job.argv)
        .envs(job.env.iter().map(|(k, v)| (k.as_str(), v.as_str())))
        .current_dir(job.workspace.join(&job.subdir));
    let result = run_child(cmd, &job, cancel).await;
    restore(&originals);
    result
}

/// A file the in-place mode touched: its path, its original content (None: did not exist)
/// and what the hypothesis wrote (None: deleted).
type Touched = (PathBuf, Option<Vec<u8>>, Option<Vec<u8>>);

fn restore(originals: &[Touched]) {
    for (path, original, written) in originals.iter().rev() {
        let current = std::fs::read(path).ok();
        if &current != written {
            tracing::warn!(
                path = %path.display(),
                "shadow run: file changed while the hypothesis ran; not restored"
            );
            continue;
        }
        let restored = match original {
            Some(bytes) => std::fs::write(path, bytes),
            None => match std::fs::remove_file(path) {
                Err(e) if e.kind() != std::io::ErrorKind::NotFound => Err(e),
                _ => Ok(()),
            },
        };
        if let Err(e) = restored {
            tracing::warn!(path = %path.display(), error = %e, "shadow run: could not restore file");
        }
    }
}

fn default_parallel() -> usize {
    std::thread::available_parallelism()
        .map(|n| (n.get() / 8).max(1))
        .unwrap_or(1)
}

/// Handles a `ShadowRunRequest` on a client connection: runs every hypothesis (in parallel as
/// overlays where the node supports them), answers pings meanwhile, kills everything if the
/// client leaves, and finishes with one `ShadowRunResponse`.
pub async fn run_shadow(
    state: &crate::ServerState,
    framed: &mut Framed<TcpStream, ProdCodeCodec>,
    req: ShadowRunRequest,
) -> Result<()> {
    let workspace = crate::workspace::server_workspace_path(
        &state.storage_root,
        &req.client_workspace_root,
        req.base_workspace_name.as_deref(),
    );
    let workspace_str = workspace.to_string_lossy().to_string();
    let refuse = |error: String| ShadowRunResponse {
        server_workspace_root: workspace_str.clone(),
        mode: String::new(),
        results: Vec::new(),
        error: Some(error),
    };
    let refusal = if !workspace.is_dir() {
        Some(format!(
            "workspace {workspace_str} is not synced to this gateway"
        ))
    } else if req.command.is_empty() {
        Some("empty command".to_string())
    } else if req.hypotheses.is_empty() {
        Some("no hypotheses".to_string())
    } else {
        let mut seen = std::collections::HashSet::new();
        req.hypotheses
            .iter()
            .find(|h| h.name.trim().is_empty() || !seen.insert(h.name.as_str()))
            .map(|h| format!("hypothesis name {:?} is empty or repeated", h.name))
    };
    if let Some(error) = refusal {
        framed
            .send(WireMessage::ShadowRunResponse(refuse(error)))
            .await?;
        return Ok(());
    }
    let subdir = match req.subdir.as_deref() {
        Some(sub)
            if !sub.is_empty()
                && !sub.starts_with('/')
                && !sub.split('/').any(|c| c == "..")
                && workspace.join(sub).is_dir() =>
        {
            sub.to_string()
        }
        _ => String::new(),
    };
    let timeout = Duration::from_secs(if req.timeout_secs == 0 {
        DEFAULT_TIMEOUT_SECS
    } else {
        req.timeout_secs
    });
    let tail_limit = if req.tail_bytes == 0 {
        DEFAULT_TAIL_BYTES
    } else {
        req.tail_bytes
    };
    let overlay_reason = tokio::task::spawn_blocking(overlay_unavailable)
        .await
        .unwrap_or(Some("overlay probe failed"));
    let overlay = overlay_reason.is_none();
    let mode = if overlay { "overlay" } else { "in-place" };
    let parallel = if !overlay {
        1
    } else if req.parallel == 0 {
        default_parallel()
    } else {
        req.parallel
    };
    if let Some(reason) = overlay_reason {
        tracing::info!(
            reason,
            "🌓 [SHADOW] overlay shadows unavailable; running in place"
        );
    }
    if overlay {
        std::fs::create_dir_all(&state.shadow_root)
            .with_context(|| format!("cannot create {}", state.shadow_root.display()))?;
    }
    let names: Vec<String> = req.hypotheses.iter().map(|h| h.name.clone()).collect();
    let count = names.len();
    tracing::info!(
        workspace = %workspace_str,
        command = %req.command.join(" "),
        hypotheses = count,
        mode,
        parallel,
        "🌓 [SHADOW] started"
    );
    let start = Instant::now();
    let (cancel_tx, cancel_rx) = tokio::sync::watch::channel(false);
    let semaphore = Arc::new(tokio::sync::Semaphore::new(parallel));
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    let mut handles = Vec::with_capacity(count);
    for hypothesis in req.hypotheses {
        let job = Job {
            name: hypothesis.name,
            files: hypothesis.files,
            argv: req.command.clone(),
            env: req.env.clone(),
            timeout,
            tail_limit,
            workspace: workspace.clone(),
            subdir: subdir.clone(),
            shadow_root: state.shadow_root.clone(),
            nonce,
        };
        let semaphore = Arc::clone(&semaphore);
        let cancel = cancel_rx.clone();
        handles.push(tokio::spawn(async move {
            let _permit = semaphore.acquire_owned().await;
            if *cancel.borrow() {
                return failed(&job.name, "cancelled: the client left".to_string());
            }
            if overlay {
                run_overlay(job, cancel).await
            } else {
                run_in_place(job, cancel).await
            }
        }));
    }
    let all = futures_util::future::join_all(handles);
    tokio::pin!(all);
    let joined = loop {
        tokio::select! {
            joined = &mut all => break joined,
            incoming = framed.next() => match incoming {
                Some(Ok(WireMessage::Ping)) => framed.send(WireMessage::Pong).await?,
                Some(Ok(WireMessage::Disconnect { .. })) | None => {
                    let _ = cancel_tx.send(true);
                    let _ = (&mut all).await;
                    tracing::info!(workspace = %workspace_str, "🌓 [SHADOW] client left; hypotheses killed");
                    return Ok(());
                }
                Some(Err(e)) => {
                    let _ = cancel_tx.send(true);
                    let _ = (&mut all).await;
                    return Err(e.into());
                }
                _ => {}
            }
        }
    };
    let results: Vec<ShadowHypothesisResult> = joined
        .into_iter()
        .zip(names.iter())
        .map(|(joined, name)| {
            joined.unwrap_or_else(|e| failed(name, format!("hypothesis task failed: {e}")))
        })
        .collect();
    for result in &results {
        let mut ev = crate::metrics::Event::blank("shadow");
        ev.agent = req
            .client_agent
            .clone()
            .unwrap_or_else(|| "unknown".to_string());
        ev.host = req
            .client_host
            .clone()
            .unwrap_or_else(|| "unknown".to_string());
        ev.workspace = workspace
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();
        ev.command = format!("{} [{}]", req.command.join(" "), result.name);
        ev.duration_ms = result.duration_ms;
        ev.exit_code = result.exit_code;
        ev.ok = result.exit_code == Some(0);
        ev.bytes = result.output_len;
        state.metrics.record(ev);
    }
    tracing::info!(
        workspace = %workspace_str,
        hypotheses = count,
        passed = results.iter().filter(|r| r.exit_code == Some(0)).count(),
        duration_ms = start.elapsed().as_millis() as u64,
        "🌓 [SHADOW] finished"
    );
    framed
        .send(WireMessage::ShadowRunResponse(ShadowRunResponse {
            server_workspace_root: workspace_str,
            mode: mode.to_string(),
            results,
            error: None,
        }))
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn job(
        workspace: &Path,
        shadow_root: &Path,
        name: &str,
        files: Vec<FileDelta>,
        argv: &[&str],
    ) -> Job {
        Job {
            name: name.to_string(),
            files,
            argv: argv.iter().map(|s| s.to_string()).collect(),
            env: Vec::new(),
            timeout: Duration::from_secs(30),
            tail_limit: 4096,
            workspace: workspace.to_path_buf(),
            subdir: String::new(),
            shadow_root: shadow_root.to_path_buf(),
            nonce: 7,
        }
    }

    fn delta(path: &str, content: Option<&str>) -> FileDelta {
        FileDelta {
            relative_path: path.to_string(),
            content: content.map(|c| c.as_bytes().to_vec()),
            is_executable: false,
        }
    }

    fn output(result: &ShadowHypothesisResult) -> String {
        String::from_utf8_lossy(result.output_tail.as_deref().unwrap_or_default()).into_owned()
    }

    #[test]
    fn tail_buffer_keeps_only_the_end_and_counts_everything() {
        let mut tail = TailBuffer::new(5);
        tail.push(b"abc");
        tail.push(b"defgh");
        tail.push(b"ij");
        assert_eq!(tail.bytes(), b"fghij");
        assert_eq!(tail.total, 10);
        tail.push(b"0123456789");
        assert_eq!(tail.bytes(), b"56789");
    }

    #[test]
    fn safe_relative_rejects_absolute_and_parent_paths() {
        assert_eq!(
            safe_relative("src/lib.rs"),
            Some(PathBuf::from("src/lib.rs"))
        );
        assert_eq!(
            safe_relative("./src/lib.rs"),
            Some(PathBuf::from("src/lib.rs"))
        );
        assert_eq!(safe_relative("/etc/passwd"), None);
        assert_eq!(safe_relative("../x"), None);
        assert_eq!(safe_relative("src/../../x"), None);
        assert_eq!(safe_relative(""), None);
    }

    #[test]
    fn stage_upper_writes_files_and_lists_deletions() {
        let upper = tempfile::tempdir().unwrap();
        let deleted = stage_upper(
            upper.path(),
            &[
                delta("crates/x/src/lib.rs", Some("pub fn x() {}\n")),
                delta("old.rs", None),
            ],
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(upper.path().join("crates/x/src/lib.rs")).unwrap(),
            "pub fn x() {}\n"
        );
        assert_eq!(deleted, vec![PathBuf::from("old.rs")]);
        assert!(stage_upper(upper.path(), &[delta("../escape", Some(""))]).is_err());
    }

    #[test]
    fn dir_names_are_filesystem_safe() {
        let name = dir_name(Path::new("/srv/ws/repo--wt-1"), "fix: use/slice", 255);
        assert_eq!(name, "repo--wt-1--fix__use_slice-ff");
    }

    #[tokio::test]
    async fn in_place_hypotheses_restore_the_workspace() {
        let ws = tempfile::tempdir().unwrap();
        std::fs::write(ws.path().join("a.txt"), "base\n").unwrap();
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let shadow = tempfile::tempdir().unwrap();
        let argv = ["sh", "-c", "cat a.txt 2>&1; ls"];
        let one = run_in_place(
            job(
                ws.path(),
                shadow.path(),
                "one",
                vec![delta("a.txt", Some("one\n")), delta("b.txt", Some("new\n"))],
                &argv,
            ),
            rx.clone(),
        )
        .await;
        assert_eq!(one.exit_code, Some(0), "{:?}", one.error);
        assert!(output(&one).contains("one") && output(&one).contains("b.txt"));
        let two = run_in_place(
            job(
                ws.path(),
                shadow.path(),
                "two",
                vec![delta("a.txt", None)],
                &argv,
            ),
            rx,
        )
        .await;
        assert_eq!(two.exit_code, Some(0));
        assert!(!output(&two).contains("base"));
        assert_eq!(
            std::fs::read_to_string(ws.path().join("a.txt")).unwrap(),
            "base\n"
        );
        assert!(!ws.path().join("b.txt").exists());
    }

    /// Needs unprivileged user namespaces + overlayfs (Linux); skipped elsewhere.
    #[tokio::test]
    async fn overlay_hypotheses_run_in_parallel_and_leave_the_workspace_untouched() {
        if let Some(reason) = overlay_unavailable() {
            eprintln!("skipped: {reason}");
            return;
        }
        let ws = tempfile::tempdir().unwrap();
        std::fs::write(ws.path().join("a.txt"), "base\n").unwrap();
        let shadow = tempfile::tempdir().unwrap();
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let argv = ["sh", "-c", "cat a.txt 2>&1; ls; echo made > made.txt"];
        let one = run_overlay(
            job(
                ws.path(),
                shadow.path(),
                "one",
                vec![delta("a.txt", Some("one\n")), delta("b.txt", Some("new\n"))],
                &argv,
            ),
            rx.clone(),
        );
        let two = run_overlay(
            job(
                ws.path(),
                shadow.path(),
                "two",
                vec![delta("a.txt", None)],
                &argv,
            ),
            rx,
        );
        let (one, two) = tokio::join!(one, two);
        assert_eq!(one.exit_code, Some(0), "{:?} {}", one.error, output(&one));
        assert!(output(&one).contains("one") && output(&one).contains("b.txt"));
        assert_eq!(two.exit_code, Some(0), "{:?} {}", two.error, output(&two));
        assert!(!output(&two).contains("base") && !output(&two).contains("a.txt\n"));
        assert_eq!(
            std::fs::read_to_string(ws.path().join("a.txt")).unwrap(),
            "base\n"
        );
        assert!(!ws.path().join("b.txt").exists());
        assert!(!ws.path().join("made.txt").exists());
        // The upper directories are removed after each hypothesis.
        tokio::time::sleep(Duration::from_millis(300)).await;
        assert_eq!(std::fs::read_dir(shadow.path()).unwrap().count(), 0);
    }

    /// `sccache` on PATH or in `~/.cargo/bin`.
    fn find_sccache() -> Option<PathBuf> {
        let on_path = std::process::Command::new("sh")
            .args(["-c", "command -v sccache"])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| PathBuf::from(String::from_utf8_lossy(&o.stdout).trim()));
        on_path.filter(|p| p.is_file()).or_else(|| {
            let home = std::env::var_os("HOME")?;
            let p = PathBuf::from(home).join(".cargo/bin/sccache");
            p.is_file().then_some(p)
        })
    }

    /// The regression of #426 on a real node: a proposed source file and a proposed build
    /// script compile through sccache inside the hypothesis's mount namespace, and the build
    /// script's output, the rlib and the test binary exist only in the shadow. It fails, rather
    /// than skips, without sccache or overlay support:
    /// `cargo test -p prod-code-gateway shadow -- --ignored --nocapture` on a Linux build node.
    #[tokio::test]
    #[ignore = "needs sccache and unprivileged overlay mounts; run with --ignored on a Linux node"]
    async fn overlay_hypotheses_compile_proposed_source_through_sccache() {
        if let Some(reason) = overlay_unavailable() {
            panic!("this test needs overlay shadows: {reason}");
        }
        let sccache = find_sccache().expect("this test needs sccache on PATH or in ~/.cargo/bin");
        // A daemon started from inside the namespace would outlive the hypothesis; start it
        // here so the wrapper only connects to it, as it does on a node with warm builds.
        let _ = std::process::Command::new(&sccache)
            .arg("--start-server")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status();
        let ws = tempfile::tempdir().unwrap();
        let shadow = tempfile::tempdir().unwrap();
        // Outside the workspace, so what the wrapper records survives the shadow.
        let tools = tempfile::tempdir().unwrap();
        let wrapper = tools.path().join("record-sccache");
        let log = tools.path().join("wrapper.log");
        std::fs::write(
            &wrapper,
            "#!/bin/sh\n\"$SHADOW_TEST_SCCACHE\" \"$@\"\nrc=$?\n\
             echo \"rc=$rc client_side=${SCCACHE_CLIENT_SIDE-unset} mntns=$(readlink /proc/self/ns/mnt) $*\" \
             >> \"$SHADOW_TEST_WRAPPER_LOG\"\nexit $rc\n",
        )
        .unwrap();
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
        std::fs::write(
            ws.path().join("Cargo.toml"),
            "[package]\nname = \"shadow-regress\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        )
        .unwrap();
        std::fs::write(
            ws.path().join("build.rs"),
            "fn main() {\n    println!(\"cargo:rustc-env=SHADOW_BUILD_RS_VAL=base\");\n}\n",
        )
        .unwrap();
        std::fs::create_dir_all(ws.path().join("src")).unwrap();
        let base_lib = "pub fn message() -> String {\n    format!(\"base:{}\", env!(\"SHADOW_BUILD_RS_VAL\"))\n}\n";
        std::fs::write(ws.path().join("src/lib.rs"), base_lib).unwrap();

        let proposed_build = r#"fn main() {
    let out = std::env::var("OUT_DIR").unwrap();
    std::fs::write(format!("{out}/marker.txt"), "marker:proposed-build-script\n").unwrap();
    println!("cargo:rustc-env=SHADOW_BUILD_RS_VAL=proposed");
}
"#;
        let proposed_lib = r#"pub fn message() -> String {
    format!("hypothesis:{}", env!("SHADOW_BUILD_RS_VAL"))
}

#[cfg(test)]
mod tests {
    #[test]
    fn sees_the_proposed_source_and_build_script() {
        assert_eq!(super::message(), "hypothesis:proposed");
    }
}
"#;
        let script = "set -e\n\
             cargo build --quiet\n\
             cargo test --quiet\n\
             ls target/debug/deps/libshadow_regress-*.rlib\n\
             cat target/debug/build/shadow-regress-*/out/marker.txt\n";
        let mut hypothesis = job(
            ws.path(),
            shadow.path(),
            "sccache",
            vec![
                delta("src/lib.rs", Some(proposed_lib)),
                delta("build.rs", Some(proposed_build)),
            ],
            &["sh", "-c", script],
        );
        hypothesis.timeout = Duration::from_secs(600);
        let target = ws.path().join("target");
        for (k, v) in [
            ("RUSTC_WRAPPER", wrapper.to_str().unwrap()),
            ("SHADOW_TEST_SCCACHE", sccache.to_str().unwrap()),
            ("SHADOW_TEST_WRAPPER_LOG", log.to_str().unwrap()),
            // sccache exits on CARGO_INCREMENTAL=1 and cannot cache incremental builds.
            ("CARGO_INCREMENTAL", "0"),
            ("CARGO_TARGET_DIR", target.to_str().unwrap()),
        ] {
            hypothesis.env.push((k.to_string(), v.to_string()));
        }
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let result = run_overlay(hypothesis, rx).await;
        let out = output(&result);
        assert_eq!(result.exit_code, Some(0), "{:?} {out}", result.error);
        assert!(out.contains("test result: ok. 1 passed"), "{out}");
        assert!(out.contains("libshadow_regress-"), "{out}");
        assert!(out.contains("marker:proposed-build-script"), "{out}");

        // Nothing reached the workspace copy: no target directory, the base files unchanged.
        assert!(!target.exists(), "the build escaped the shadow");
        assert_eq!(
            std::fs::read_to_string(ws.path().join("src/lib.rs")).unwrap(),
            base_lib
        );
        assert!(
            std::fs::read_to_string(ws.path().join("build.rs"))
                .unwrap()
                .contains("=base")
        );

        // sccache itself ran for the build script and the library, inside another mount
        // namespace, with client-side mode on, and succeeded.
        let recorded = std::fs::read_to_string(&log).expect("the wrapper was never invoked");
        let own_ns = std::fs::read_link("/proc/self/ns/mnt").unwrap();
        let own_ns = format!("mntns={}", own_ns.display());
        for krate in ["build_script_build", "shadow_regress"] {
            let calls: Vec<&str> = recorded
                .lines()
                .filter(|l| l.contains(&format!("--crate-name {krate} ")))
                .collect();
            assert!(!calls.is_empty(), "no sccache call for {krate}: {recorded}");
            for call in calls {
                assert!(call.starts_with("rc=0 client_side=1 mntns="), "{call}");
                assert!(
                    !call.contains(&own_ns),
                    "compiled outside the shadow: {call}"
                );
            }
        }
        for line in recorded.lines() {
            let crate_name = line
                .split("--crate-name ")
                .nth(1)
                .and_then(|rest| rest.split(' ').next())
                .unwrap_or("-");
            eprintln!(
                "wrapper: {} crate={crate_name}",
                line.split(' ').take(3).collect::<Vec<_>>().join(" ")
            );
        }
    }

    /// `sccache_client_side` with exactly these variables and nothing from the process.
    fn verdict(
        vars: &[(&str, &str)],
        workspace: &Path,
        files: &[FileDelta],
    ) -> std::result::Result<(), String> {
        let var = |key: &str| {
            vars.iter()
                .rev()
                .find(|(k, _)| *k == key)
                .map(|(_, v)| OsString::from(v))
        };
        sccache_client_side(&var, workspace, files)
    }

    fn refused(verdict: std::result::Result<(), String>, needle: &str) {
        let why = verdict.expect_err("expected a refusal");
        assert!(why.contains(needle), "{why:?} does not mention {needle:?}");
    }

    const SCHEDULER_TOML: &str = "[dist]\nscheduler_url = \"https://scheduler.invalid\"\n[dist.auth]\ntype = \"token\"\ntoken = \"hunter2\"\n";

    #[test]
    fn sccache_client_side_values_that_are_not_on_are_refused() {
        let home = tempfile::tempdir().unwrap();
        let ws = tempfile::tempdir().unwrap();
        let h = home.path().to_str().unwrap();
        for on in ["1", "true", "TRUE", "on", "On"] {
            verdict(&[("HOME", h), ("SCCACHE_CLIENT_SIDE", on)], ws.path(), &[])
                .unwrap_or_else(|e| panic!("{on}: {e}"));
        }
        for off in ["0", "false", "FALSE", "off", "Off"] {
            refused(
                verdict(&[("HOME", h), ("SCCACHE_CLIENT_SIDE", off)], ws.path(), &[]),
                "turns sccache's client-side mode off",
            );
        }
        // sccache fails on these, so they cannot silently disable it either.
        for bad in ["no", "yes", "2", " 1", "enabled"] {
            refused(
                verdict(&[("HOME", h), ("SCCACHE_CLIENT_SIDE", bad)], ws.path(), &[]),
                "is not one of true, on, 1",
            );
        }
        // Empty or unset falls back to the config file, which does not enable it.
        refused(
            verdict(&[("HOME", h), ("SCCACHE_CLIENT_SIDE", "")], ws.path(), &[]),
            "client_side_mode = true",
        );
        refused(
            verdict(&[("HOME", h)], ws.path(), &[]),
            "SCCACHE_CLIENT_SIDE is empty",
        );
    }

    #[test]
    fn sccache_log_disables_client_side_mode_but_error_log_does_not() {
        let home = tempfile::tempdir().unwrap();
        let ws = tempfile::tempdir().unwrap();
        let h = home.path().to_str().unwrap();
        let base = [("HOME", h), ("SCCACHE_CLIENT_SIDE", "1")];
        refused(
            verdict(
                &[base[0], base[1], ("SCCACHE_LOG", "debug")],
                ws.path(),
                &[],
            ),
            "SCCACHE_LOG",
        );
        refused(
            verdict(&[base[0], base[1], ("SCCACHE_LOG", "")], ws.path(), &[]),
            "SCCACHE_LOG",
        );
        // Only the daemon's stderr goes there; the client-side mode is unaffected.
        verdict(
            &[base[0], base[1], ("SCCACHE_ERROR_LOG", "/tmp/sccache.log")],
            ws.path(),
            &[],
        )
        .unwrap();
    }

    #[test]
    fn sccache_scheduler_in_the_default_config_is_refused() {
        let home = tempfile::tempdir().unwrap();
        let xdg = tempfile::tempdir().unwrap();
        let ws = tempfile::tempdir().unwrap();
        let (h, x) = (home.path().to_str().unwrap(), xdg.path().to_str().unwrap());
        let home_conf = home.path().join(".config/sccache/config");
        std::fs::create_dir_all(home_conf.parent().unwrap()).unwrap();
        std::fs::write(&home_conf, SCHEDULER_TOML).unwrap();
        let why =
            verdict(&[("HOME", h), ("SCCACHE_CLIENT_SIDE", "1")], ws.path(), &[]).unwrap_err();
        assert!(why.contains("dist.scheduler_url"), "{why}");
        assert!(why.contains(&home_conf.display().to_string()), "{why}");
        assert!(!why.contains("hunter2"), "credentials leaked: {why}");
        // A relative XDG_CONFIG_HOME is ignored, as the directories crate does.
        refused(
            verdict(
                &[
                    ("HOME", h),
                    ("XDG_CONFIG_HOME", "rel"),
                    ("SCCACHE_CLIENT_SIDE", "1"),
                ],
                ws.path(),
                &[],
            ),
            "dist.scheduler_url",
        );
        // An absolute XDG_CONFIG_HOME replaces ~/.config.
        verdict(
            &[
                ("HOME", h),
                ("XDG_CONFIG_HOME", x),
                ("SCCACHE_CLIENT_SIDE", "1"),
            ],
            ws.path(),
            &[],
        )
        .unwrap();
        std::fs::create_dir_all(xdg.path().join("sccache")).unwrap();
        std::fs::write(xdg.path().join("sccache/config"), SCHEDULER_TOML).unwrap();
        refused(
            verdict(
                &[("XDG_CONFIG_HOME", x), ("SCCACHE_CLIENT_SIDE", "1")],
                ws.path(),
                &[],
            ),
            "dist.scheduler_url",
        );
        // A dist section without a scheduler is local compilation.
        std::fs::write(
            &home_conf,
            "[dist]\ncache_dir = \"/tmp/x\"\n[cache.disk]\ndir = \"/tmp/c\"\n",
        )
        .unwrap();
        verdict(&[("HOME", h), ("SCCACHE_CLIENT_SIDE", "1")], ws.path(), &[]).unwrap();
    }

    #[test]
    fn sccache_conf_overrides_the_default_config() {
        let home = tempfile::tempdir().unwrap();
        let conf = tempfile::tempdir().unwrap();
        let ws = tempfile::tempdir().unwrap();
        let h = home.path().to_str().unwrap();
        let home_conf = home.path().join(".config/sccache/config");
        std::fs::create_dir_all(home_conf.parent().unwrap()).unwrap();
        std::fs::write(&home_conf, SCHEDULER_TOML).unwrap();
        // An explicit safe config wins over the default one with a scheduler.
        let safe = conf.path().join("safe.toml");
        std::fs::write(
            &safe,
            "client_side_mode = true\n[cache.disk]\ndir = \"/tmp/c\"\n",
        )
        .unwrap();
        let s = safe.to_str().unwrap();
        verdict(
            &[
                ("HOME", h),
                ("SCCACHE_CONF", s),
                ("SCCACHE_CLIENT_SIDE", "1"),
            ],
            ws.path(),
            &[],
        )
        .unwrap();
        // With SCCACHE_CLIENT_SIDE empty the file's client_side_mode decides.
        verdict(
            &[
                ("HOME", h),
                ("SCCACHE_CONF", s),
                ("SCCACHE_CLIENT_SIDE", ""),
            ],
            ws.path(),
            &[],
        )
        .unwrap();
        // A non-empty variable wins over the file.
        refused(
            verdict(
                &[("SCCACHE_CONF", s), ("SCCACHE_CLIENT_SIDE", "off")],
                ws.path(),
                &[],
            ),
            "client-side mode off",
        );
        // A missing SCCACHE_CONF file is no config, as for sccache.
        let missing = conf.path().join("missing.toml");
        verdict(
            &[
                ("SCCACHE_CONF", missing.to_str().unwrap()),
                ("SCCACHE_CLIENT_SIDE", "1"),
            ],
            ws.path(),
            &[],
        )
        .unwrap();
        // JSON by extension: a null scheduler is none, a string one is distributed.
        let json = conf.path().join("conf.json");
        let j = json.to_str().unwrap();
        std::fs::write(
            &json,
            r#"{"dist": {"scheduler_url": null}, "client_side_mode": true}"#,
        )
        .unwrap();
        verdict(
            &[("SCCACHE_CONF", j), ("SCCACHE_CLIENT_SIDE", "")],
            ws.path(),
            &[],
        )
        .unwrap();
        std::fs::write(&json, r#"{"dist": {"scheduler_url": "https://s.invalid"}}"#).unwrap();
        refused(
            verdict(
                &[("SCCACHE_CONF", j), ("SCCACHE_CLIENT_SIDE", "1")],
                ws.path(),
                &[],
            ),
            "dist.scheduler_url",
        );
        // Relative or empty paths depend on each compiler's working directory.
        for rel in ["sccache.toml", ""] {
            refused(
                verdict(
                    &[("SCCACHE_CONF", rel), ("SCCACHE_CLIENT_SIDE", "1")],
                    ws.path(),
                    &[],
                ),
                "SCCACHE_CONF must be an absolute path",
            );
        }
        refused(
            verdict(&[("SCCACHE_CLIENT_SIDE", "1")], ws.path(), &[]),
            "cannot locate the sccache config",
        );
    }

    #[test]
    fn invalid_or_unreadable_sccache_configs_are_refused_without_their_content() {
        let conf = tempfile::tempdir().unwrap();
        let ws = tempfile::tempdir().unwrap();
        let cases = [
            (
                "bad.toml",
                "token = \"hunter2\"\n[dist\n",
                "is not valid TOML",
            ),
            ("bad.json", "{\"token\": \"hunter2\",", "is not valid JSON"),
            ("list.json", "[\"hunter2\"]", "is not a table"),
            (
                "dist.toml",
                "dist = \"hunter2\"\n",
                "`dist` that is not a table",
            ),
            (
                "mode.toml",
                "client_side_mode = \"hunter2\"\n",
                "not a boolean",
            ),
        ];
        for (name, content, needle) in cases {
            let path = conf.path().join(name);
            std::fs::write(&path, content).unwrap();
            let why = verdict(
                &[
                    ("SCCACHE_CONF", path.to_str().unwrap()),
                    ("SCCACHE_CLIENT_SIDE", "1"),
                ],
                ws.path(),
                &[],
            )
            .unwrap_err();
            assert!(why.contains(needle), "{name}: {why}");
            assert!(!why.contains("hunter2"), "{name}: content leaked: {why}");
        }
        let binary = conf.path().join("binary");
        std::fs::write(&binary, [0xff, 0xfe, 0x00]).unwrap();
        refused(
            verdict(
                &[
                    ("SCCACHE_CONF", binary.to_str().unwrap()),
                    ("SCCACHE_CLIENT_SIDE", "1"),
                ],
                ws.path(),
                &[],
            ),
            "is not UTF-8 text",
        );
        // A directory where the file should be cannot be read.
        refused(
            verdict(
                &[
                    ("SCCACHE_CONF", conf.path().to_str().unwrap()),
                    ("SCCACHE_CLIENT_SIDE", "1"),
                ],
                ws.path(),
                &[],
            ),
            "cannot read the sccache config",
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let locked = conf.path().join("locked.toml");
            std::fs::write(&locked, SCHEDULER_TOML).unwrap();
            std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o000)).unwrap();
            // Root reads it anyway; the refusal is only observable for other users.
            if std::fs::read(&locked).is_err() {
                refused(
                    verdict(
                        &[
                            ("SCCACHE_CONF", locked.to_str().unwrap()),
                            ("SCCACHE_CLIENT_SIDE", "1"),
                        ],
                        ws.path(),
                        &[],
                    ),
                    "cannot read the sccache config",
                );
            }
        }
    }

    #[test]
    fn a_proposed_sccache_config_inside_the_workspace_is_what_counts() {
        let ws = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(ws.path().join("ci")).unwrap();
        let path = ws.path().join("ci/sccache.toml");
        let p = path.to_str().unwrap();
        let vars = [("SCCACHE_CONF", p), ("SCCACHE_CLIENT_SIDE", "1")];
        std::fs::write(&path, "[cache.disk]\ndir = \"/tmp/c\"\n").unwrap();
        verdict(&vars, ws.path(), &[]).unwrap();
        refused(
            verdict(
                &vars,
                ws.path(),
                &[delta("ci/sccache.toml", Some(SCHEDULER_TOML))],
            ),
            "dist.scheduler_url",
        );
        refused(
            verdict(
                &vars,
                ws.path(),
                &[delta("./ci/sccache.toml", Some("[dist"))],
            ),
            "is not valid TOML",
        );
        std::fs::write(&path, SCHEDULER_TOML).unwrap();
        refused(verdict(&vars, ws.path(), &[]), "dist.scheduler_url");
        verdict(
            &vars,
            ws.path(),
            &[delta("ci/sccache.toml", Some("client_side_mode = true\n"))],
        )
        .unwrap();
        // Deletions run after the upper directory is mounted, so they win over content.
        verdict(&vars, ws.path(), &[delta("ci/sccache.toml", None)]).unwrap();
        verdict(
            &vars,
            ws.path(),
            &[
                delta("ci/sccache.toml", Some(SCHEDULER_TOML)),
                delta("ci", None),
            ],
        )
        .unwrap();
        // Other proposed files leave the one on disk in force.
        refused(
            verdict(&vars, ws.path(), &[delta("ci/other.toml", Some(""))]),
            "dist.scheduler_url",
        );
    }

    #[test]
    fn aliases_of_a_proposed_sccache_config_resolve_as_in_the_hypothesis() {
        use std::os::unix::fs::symlink;
        let ws = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let (w, o) = (ws.path(), outside.path());
        let safe = "[cache.disk]\ndir = \"/tmp/c\"\n";
        std::fs::create_dir_all(w.join("ci")).unwrap();
        std::fs::write(w.join("sccache.toml"), safe).unwrap();
        std::fs::write(w.join("ci/sccache.toml"), safe).unwrap();
        let check = |conf: &Path, files: &[FileDelta]| {
            verdict(
                &[
                    ("SCCACHE_CONF", conf.to_str().unwrap()),
                    ("SCCACHE_CLIENT_SIDE", "1"),
                ],
                w,
                files,
            )
        };
        let scheduler = |rel: &str| vec![delta(rel, Some(SCHEDULER_TOML))];

        // A parent component: the proposed file is the one the path resolves to.
        let dotdot = w.join("ci/../sccache.toml");
        check(&dotdot, &[]).unwrap();
        refused(
            check(&dotdot, &scheduler("sccache.toml")),
            "dist.scheduler_url",
        );
        // Through a directory only the hypothesis creates; without it the path does not exist.
        let staged = w.join("new/../sccache.toml");
        check(&staged, &scheduler("sccache.toml")).unwrap();
        refused(
            check(
                &staged,
                &[
                    delta("new/keep.txt", Some("")),
                    delta("sccache.toml", Some(SCHEDULER_TOML)),
                ],
            ),
            "dist.scheduler_url",
        );

        // Symlinks outside the workspace into it, to the file and to its directory.
        symlink(w.join("ci/sccache.toml"), o.join("into.toml")).unwrap();
        symlink(w.join("ci"), o.join("intodir")).unwrap();
        for conf in [o.join("into.toml"), o.join("intodir/sccache.toml")] {
            check(&conf, &[]).unwrap();
            refused(
                check(&conf, &scheduler("ci/sccache.toml")),
                "dist.scheduler_url",
            );
            // Deleting the directory still wins over its proposed content.
            check(
                &conf,
                &[
                    delta("ci/sccache.toml", Some(SCHEDULER_TOML)),
                    delta("ci", None),
                ],
            )
            .unwrap();
        }
        // A symlink inside the workspace to another file in it.
        symlink("ci/sccache.toml", w.join("link.toml")).unwrap();
        refused(
            check(&w.join("link.toml"), &scheduler("ci/sccache.toml")),
            "dist.scheduler_url",
        );
        // The workspace named through a symlink is mounted where it resolves to.
        symlink(w, o.join("ws")).unwrap();
        refused(
            verdict(
                &[
                    ("SCCACHE_CONF", w.join("sccache.toml").to_str().unwrap()),
                    ("SCCACHE_CLIENT_SIDE", "1"),
                ],
                &o.join("ws"),
                &scheduler("sccache.toml"),
            ),
            "dist.scheduler_url",
        );

        // Deleting through a symlinked directory removes the file it points into.
        symlink("ci", w.join("lnk")).unwrap();
        std::fs::write(w.join("ci/sccache.toml"), SCHEDULER_TOML).unwrap();
        let in_ci = w.join("ci/sccache.toml");
        refused(check(&in_ci, &[]), "dist.scheduler_url");
        check(&in_ci, &[delta("lnk/sccache.toml", None)]).unwrap();
        // A staged directory hides a symlink of the same name and what it points to.
        let via_lnk = w.join("lnk/sccache.toml");
        refused(check(&via_lnk, &[]), "dist.scheduler_url");
        check(&via_lnk, &[delta("lnk/other.toml", Some(""))]).unwrap();

        // A proposed file replaces a symlink as a regular file; its target no longer counts.
        std::fs::write(o.join("out.toml"), SCHEDULER_TOML).unwrap();
        symlink(o.join("out.toml"), w.join("out.toml")).unwrap();
        let out = w.join("out.toml");
        refused(check(&out, &[]), "dist.scheduler_url");
        check(&out, &[delta("out.toml", Some(safe))]).unwrap();
        refused(
            check(&o.join("out.toml"), &[delta("out.toml", Some(safe))]),
            "dist.scheduler_url",
        );
        std::fs::write(o.join("out.toml"), safe).unwrap();
        check(&out, &[]).unwrap();
        refused(check(&out, &scheduler("out.toml")), "dist.scheduler_url");
        // Deleting the symlink removes the link, not its target.
        std::fs::write(o.join("out.toml"), SCHEDULER_TOML).unwrap();
        check(&out, &[delta("out.toml", None)]).unwrap();
        refused(
            check(&o.join("out.toml"), &[delta("out.toml", None)]),
            "dist.scheduler_url",
        );

        // A symlink loop is refused rather than guessed.
        symlink("loop", w.join("loop")).unwrap();
        refused(
            check(&w.join("loop"), &[]),
            "too many levels of symbolic links",
        );
    }

    /// The validator against the kernel: for each alias, the config the validator reads is
    /// what `cat` reads inside the hypothesis. Needs overlay shadows; skipped elsewhere.
    #[tokio::test]
    async fn aliased_sccache_configs_read_what_the_overlay_command_reads() {
        if let Some(reason) = overlay_unavailable() {
            eprintln!("skipped: {reason}");
            return;
        }
        use std::os::unix::fs::symlink;
        let ws = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let shadow = tempfile::tempdir().unwrap();
        let (w, o) = (ws.path(), outside.path());
        std::fs::create_dir_all(w.join("ci")).unwrap();
        std::fs::write(w.join("sccache.toml"), "# disk root\n").unwrap();
        std::fs::write(w.join("ci/sccache.toml"), "# disk ci\n").unwrap();
        std::fs::write(o.join("outside.toml"), "# outside\n").unwrap();
        symlink("ci", w.join("lnk")).unwrap();
        symlink("ci/sccache.toml", w.join("link.toml")).unwrap();
        symlink(o.join("outside.toml"), w.join("out.toml")).unwrap();
        symlink(w.join("ci/sccache.toml"), o.join("into.toml")).unwrap();
        symlink(w.join("ci"), o.join("intodir")).unwrap();
        let root = || delta("sccache.toml", Some("# proposed root\n"));
        let ci = || delta("ci/sccache.toml", Some("# proposed ci\n"));
        let cases: Vec<(PathBuf, Vec<FileDelta>)> = vec![
            (w.join("ci/../sccache.toml"), vec![root()]),
            (w.join("new/../sccache.toml"), vec![root()]),
            (
                w.join("new/../sccache.toml"),
                vec![delta("new/keep.txt", Some("")), root()],
            ),
            (o.join("into.toml"), vec![ci()]),
            (o.join("intodir/sccache.toml"), vec![ci()]),
            (
                o.join("intodir/sccache.toml"),
                vec![ci(), delta("ci", None)],
            ),
            (w.join("link.toml"), vec![ci()]),
            (w.join("out.toml"), vec![]),
            (
                w.join("out.toml"),
                vec![delta("out.toml", Some("# proposed out\n"))],
            ),
            (w.join("out.toml"), vec![delta("out.toml", None)]),
            (o.join("outside.toml"), vec![delta("out.toml", None)]),
            (w.join("lnk/sccache.toml"), vec![]),
            (
                w.join("lnk/sccache.toml"),
                vec![delta("lnk/other.toml", Some(""))],
            ),
            (
                w.join("ci/sccache.toml"),
                vec![delta("lnk/sccache.toml", None)],
            ),
        ];
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let argv = [
            "sh",
            "-c",
            "cat \"$SCCACHE_CONF\" 2>/dev/null || echo missing",
        ];
        for (i, (conf, files)) in cases.into_iter().enumerate() {
            let expected = match sccache_config_content(&conf, w, &files).unwrap() {
                Some(bytes) => String::from_utf8(bytes).unwrap(),
                None => "missing\n".to_string(),
            };
            let what = format!("case {i}: {}", conf.display());
            let mut j = job(w, shadow.path(), &format!("alias-{i}"), files, &argv);
            j.env = vec![(
                "SCCACHE_CONF".to_string(),
                conf.to_str().unwrap().to_string(),
            )];
            let r = run_overlay(j, rx.clone()).await;
            assert_eq!(r.exit_code, Some(0), "{what}: {:?}", r.error);
            assert_eq!(output(&r), expected, "{what}");
        }
        assert_eq!(
            std::fs::read_to_string(o.join("outside.toml")).unwrap(),
            "# outside\n"
        );
        assert_eq!(
            std::fs::read_to_string(w.join("ci/sccache.toml")).unwrap(),
            "# disk ci\n"
        );
    }

    #[test]
    fn effective_env_is_the_request_over_the_gateway() {
        let env = vec![
            ("PATH".to_string(), "/first".to_string()),
            ("PATH".to_string(), "/last".to_string()),
        ];
        assert_eq!(effective_var(&env, "PATH"), Some(OsString::from("/last")));
        assert_eq!(effective_var(&[], "PATH"), std::env::var_os("PATH"));
        // run_overlay sets SCCACHE_CLIENT_SIDE=1 unless the request overrides it.
        assert_eq!(
            effective_var(&[], "SCCACHE_CLIENT_SIDE"),
            Some(OsString::from("1"))
        );
        let off = vec![("SCCACHE_CLIENT_SIDE".to_string(), String::new())];
        assert_eq!(
            effective_var(&off, "SCCACHE_CLIENT_SIDE"),
            Some(OsString::new())
        );
    }

    #[tokio::test]
    async fn overlay_hypotheses_refuse_sccache_settings_before_running() {
        let ws = tempfile::tempdir().unwrap();
        let shadow = tempfile::tempdir().unwrap();
        let conf = tempfile::tempdir().unwrap();
        let safe = conf.path().join("safe.toml");
        std::fs::write(&safe, "").unwrap();
        let safe = safe.to_str().unwrap();
        let in_ws = ws.path().join("sccache.toml");
        let in_ws = in_ws.to_str().unwrap();
        let (_tx, rx) = tokio::sync::watch::channel(false);
        // Would leave a file in the shadow root if the command ran.
        let argv = ["sh", "-c", "echo ran"];
        let cases = [
            (
                "log",
                vec![("SCCACHE_CONF", safe), ("SCCACHE_LOG", "info")],
                vec![],
                "SCCACHE_LOG",
            ),
            (
                "empty",
                vec![("SCCACHE_CONF", safe), ("SCCACHE_CLIENT_SIDE", "")],
                vec![],
                "SCCACHE_CLIENT_SIDE is empty",
            ),
            (
                "no",
                vec![("SCCACHE_CONF", safe), ("SCCACHE_CLIENT_SIDE", "no")],
                vec![],
                "SCCACHE_CLIENT_SIDE is not one of",
            ),
            (
                "proposed-scheduler",
                vec![("SCCACHE_CONF", in_ws)],
                vec![delta("sccache.toml", Some(SCHEDULER_TOML))],
                "dist.scheduler_url",
            ),
        ];
        for (name, env, files, needle) in cases {
            let mut j = job(ws.path(), shadow.path(), name, files, &argv);
            j.env = env
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            let r = run_overlay(j, rx.clone()).await;
            assert!(
                r.exit_code.is_none() && r.output_tail.is_none(),
                "{name} ran"
            );
            let why = r.error.unwrap_or_default();
            assert!(
                why.starts_with("cannot run an overlay shadow: "),
                "{name}: {why}"
            );
            assert!(why.contains(needle), "{name}: {why}");
            assert!(!why.contains("hunter2"), "{name}: {why}");
        }
        // Refused before staging: nothing was created under the shadow root.
        assert_eq!(std::fs::read_dir(shadow.path()).unwrap().count(), 0);
    }
}
